using System;
using System.IO;
using Meta.Adapters;
using Meta.Core.Domain;
using Meta.Core.Services;

namespace Meta.Core.Tests;

public sealed class GenerationServiceTests
{
    [Fact]
    public async Task GenerateSql_IsDeterministicAcrossRuns()
    {
        var services = new ServiceCollection();
        var (workspace, sampleRoot) = await TestWorkspaceFactory.LoadCanonicalSampleWorkspaceAsync(services);
        var outputA = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "a");
        var outputB = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "b");

        try
        {
            var manifestA = GenerationService.GenerateSql(workspace, outputA);
            var manifestB = GenerationService.GenerateSql(workspace, outputB);

            Assert.True(GenerationService.AreEquivalent(manifestA, manifestB, out var message), message);
            Assert.True(File.Exists(Path.Combine(outputA, "schema.sql")));
            Assert.True(File.Exists(Path.Combine(outputA, "data.sql")));
            var schemaText = await File.ReadAllTextAsync(Path.Combine(outputA, "schema.sql"));
            Assert.Contains("NVARCHAR(MAX)", schemaText, StringComparison.Ordinal);
        }
        finally
        {
            TestWorkspaceFactory.DeleteDirectorySafe(sampleRoot);
            DeleteDirectoryIfExists(Path.GetDirectoryName(outputA)!);
            DeleteDirectoryIfExists(Path.GetDirectoryName(outputB)!);
        }
    }

    [Fact]
    public async Task GenerateSsdt_WritesExpectedFiles()
    {
        var services = new ServiceCollection();
        var (workspace, sampleRoot) = await TestWorkspaceFactory.LoadCanonicalSampleWorkspaceAsync(services);
        var output = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "ssdt");

        try
        {
            var manifest = GenerationService.GenerateSsdt(workspace, output);

            Assert.True(File.Exists(Path.Combine(output, "Schema.sql")));
            Assert.True(File.Exists(Path.Combine(output, "Data.sql")));
            Assert.True(File.Exists(Path.Combine(output, "PostDeploy.sql")));
            Assert.True(File.Exists(Path.Combine(output, "Metadata.sqlproj")));
            Assert.Equal(4, manifest.FileHashes.Count);
        }
        finally
        {
            TestWorkspaceFactory.DeleteDirectorySafe(sampleRoot);
            DeleteDirectoryIfExists(Path.GetDirectoryName(output)!);
        }
    }

    [Fact]
    public async Task GenerateCSharp_IsDeterministicAcrossRuns()
    {
        var services = new ServiceCollection();
        var (workspace, sampleRoot) = await TestWorkspaceFactory.LoadCanonicalSampleWorkspaceAsync(services);
        var outputA = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "a");
        var outputB = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "b");

        try
        {
            var manifestA = GenerationService.GenerateCSharp(workspace, outputA);
            var manifestB = GenerationService.GenerateCSharp(workspace, outputB);
            var headerWorkspacePath = ResolveHeaderWorkspacePath(workspace);

            Assert.True(GenerationService.AreEquivalent(manifestA, manifestB, out var message), message);
            Assert.True(File.Exists(Path.Combine(outputA, workspace.Model.Name + ".cs")));
            Assert.True(File.Exists(Path.Combine(outputA, "Cube.cs")));
            var modelText = await File.ReadAllTextAsync(Path.Combine(outputA, workspace.Model.Name + ".cs"));
            var entityText = await File.ReadAllTextAsync(Path.Combine(outputA, "Cube.cs"));
            Assert.Contains("// <auto-generated>", modelText, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", modelText, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir>", modelText, StringComparison.Ordinal);
            Assert.Contains("// <auto-generated>", entityText, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", entityText, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir>", entityText, StringComparison.Ordinal);
            Assert.Contains($"public static partial class {workspace.Model.Name}", modelText, StringComparison.Ordinal);
            Assert.Contains("public static IReadOnlyList<Measure> MeasureList", modelText, StringComparison.Ordinal);
            Assert.Contains("MeasureName = \"number_of_things\"", modelText, StringComparison.Ordinal);
            Assert.DoesNotContain("Signature", modelText, StringComparison.Ordinal);
            Assert.DoesNotContain("ModelDefinitionXml", modelText, StringComparison.Ordinal);
            Assert.DoesNotContain("CreateFromWorkspace", modelText, StringComparison.Ordinal);
        }
        finally
        {
            TestWorkspaceFactory.DeleteDirectorySafe(sampleRoot);
            DeleteDirectoryIfExists(Path.GetDirectoryName(outputA)!);
            DeleteDirectoryIfExists(Path.GetDirectoryName(outputB)!);
        }
    }

    [Fact]
    public async Task GenerateCSharp_WithTooling_EmitsToolingFile()
    {
        var services = new ServiceCollection();
        var (workspace, sampleRoot) = await TestWorkspaceFactory.LoadCanonicalSampleWorkspaceAsync(services);
        var output = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "tooling");

        try
        {
            var manifest = GenerationService.GenerateCSharp(workspace, output, includeTooling: true);
            var headerWorkspacePath = ResolveHeaderWorkspacePath(workspace);
            var modelFile = workspace.Model.Name + "Model.cs";
            var toolingFile = workspace.Model.Name + ".Tooling.cs";
            var modelXmlFile = "model.xml";
            var modelPath = Path.Combine(output, modelFile);
            var toolingPath = Path.Combine(output, toolingFile);
            var modelXmlPath = Path.Combine(output, modelXmlFile);

            Assert.True(File.Exists(modelPath));
            Assert.True(File.Exists(toolingPath));
            Assert.True(File.Exists(modelXmlPath));
            Assert.True(manifest.FileHashes.ContainsKey(modelFile));
            Assert.True(manifest.FileHashes.ContainsKey(toolingFile));
            Assert.True(manifest.FileHashes.ContainsKey(modelXmlFile));
            var modelCode = File.ReadAllText(modelPath);
            var toolingCode = File.ReadAllText(toolingPath);
            Assert.Contains("// <auto-generated>", modelCode, StringComparison.Ordinal);
            Assert.Contains("// <auto-generated>", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", modelCode, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir> --tooling", modelCode, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir> --tooling", toolingCode, StringComparison.Ordinal);
            var entityCode = File.ReadAllText(Path.Combine(output, "Cube.cs"));
            Assert.Contains($"Source workspace: {headerWorkspacePath}", entityCode, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir> --tooling", entityCode, StringComparison.Ordinal);
            Assert.Contains($"public sealed partial class {workspace.Model.Name}Model", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("_builtIn", modelCode, StringComparison.Ordinal);
            Assert.Contains($"public static {workspace.Model.Name}Model CreateEmpty()", modelCode, StringComparison.Ordinal);
            Assert.Contains("public void SaveToXmlWorkspace(string workspacePath)", modelCode, StringComparison.Ordinal);
            Assert.Contains("public Task SaveToXmlWorkspaceAsync(", modelCode, StringComparison.Ordinal);
            Assert.Contains($"public static {workspace.Model.Name}Model LoadFromXmlWorkspace(", modelCode, StringComparison.Ordinal);
            Assert.Contains($"public static Task<{workspace.Model.Name}Model> LoadFromXmlWorkspaceAsync(", modelCode, StringComparison.Ordinal);
            Assert.Contains("[XmlRoot(", modelCode, StringComparison.Ordinal);
            Assert.Contains("[XmlArrayItem(", modelCode, StringComparison.Ordinal);
            Assert.Contains("TypedWorkspaceXmlSerializer.Load", modelCode, StringComparison.Ordinal);
            Assert.Contains("TypedWorkspaceXmlSerializer.Save", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("Signature", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("ModelDefinitionXml", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("CreateModelDefinition", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("CreateFromWorkspace", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("GenericRecord", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("GenericInstance", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("GenericModel", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("XElement", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("XDocument", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("MergeShard", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("WriteDocument", modelCode, StringComparison.Ordinal);
            Assert.Contains($"public static class {workspace.Model.Name}Tooling", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"public static {workspace.Model.Name}Model Load(", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"public static Task<{workspace.Model.Name}Model> LoadAsync(", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"public static void Save({workspace.Model.Name}Model model, string workspacePath)", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"public static Task SaveAsync({workspace.Model.Name}Model model, string workspacePath,", toolingCode, StringComparison.Ordinal);
            Assert.DoesNotContain("LoadWorkspaceAsync", toolingCode, StringComparison.Ordinal);
            Assert.DoesNotContain("SaveWorkspaceAsync", toolingCode, StringComparison.Ordinal);
            Assert.DoesNotContain("ImportSqlAsync", toolingCode, StringComparison.Ordinal);
            Assert.DoesNotContain("Task<Workspace>", toolingCode, StringComparison.Ordinal);
            Assert.DoesNotContain("Workspace workspace", toolingCode, StringComparison.Ordinal);
        }
        finally
        {
            TestWorkspaceFactory.DeleteDirectorySafe(sampleRoot);
            DeleteDirectoryIfExists(Path.GetDirectoryName(output)!);
        }
    }

    [Fact]
    public void GenerateCSharp_ModelAndEntityNameCollision_UsesModelSuffixForFacade()
    {
        var workspace = new Workspace
        {
            Model =
            {
                Name = "Architecture",
                Entities =
                {
                    new GenericEntity
                    {
                        Name = "Architecture",
                        Properties =
                        {
                            new GenericProperty { Name = "Name" },
                        },
                    },
                },
            },
            Instance =
            {
                ModelName = "Architecture",
            },
        };
        workspace.Instance.GetOrCreateEntityRecords("Architecture").Add(new GenericRecord
        {
            Id = "1",
            Values =
            {
                ["Name"] = "FrameworkArchitecture",
            },
        });

        var output = Path.Combine(Path.GetTempPath(), "metadata-gen-tests", Guid.NewGuid().ToString("N"), "collision");

        try
        {
            var manifest = GenerationService.GenerateCSharp(workspace, output, includeTooling: true);
            var headerWorkspacePath = ResolveHeaderWorkspacePath(workspace);
            var modelPath = Path.Combine(output, "ArchitectureModel.cs");
            var toolingPath = Path.Combine(output, "Architecture.Tooling.cs");
            var entityPath = Path.Combine(output, "Architecture.cs");

            Assert.True(File.Exists(modelPath));
            Assert.True(File.Exists(toolingPath));
            Assert.True(File.Exists(entityPath));
            Assert.True(manifest.FileHashes.ContainsKey("ArchitectureModel.cs"));
            Assert.True(manifest.FileHashes.ContainsKey("Architecture.Tooling.cs"));
            Assert.True(manifest.FileHashes.ContainsKey("Architecture.cs"));

            var modelCode = File.ReadAllText(modelPath);
            var toolingCode = File.ReadAllText(toolingPath);
            var entityCode = File.ReadAllText(entityPath);

            Assert.Contains("// <auto-generated>", modelCode, StringComparison.Ordinal);
            Assert.Contains("// <auto-generated>", toolingCode, StringComparison.Ordinal);
            Assert.Contains("// <auto-generated>", entityCode, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", modelCode, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", toolingCode, StringComparison.Ordinal);
            Assert.Contains($"Source workspace: {headerWorkspacePath}", entityCode, StringComparison.Ordinal);
            Assert.Contains($"meta generate csharp --workspace \"{headerWorkspacePath}\" --out <dir> --tooling", entityCode, StringComparison.Ordinal);
            Assert.Contains("namespace Architecture", modelCode, StringComparison.Ordinal);
            Assert.Contains("public sealed partial class ArchitectureModel", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("_builtIn", modelCode, StringComparison.Ordinal);
            Assert.Contains("public List<Architecture> ArchitectureList", modelCode, StringComparison.Ordinal);
            Assert.Contains("public static ArchitectureModel CreateEmpty()", modelCode, StringComparison.Ordinal);
            Assert.Contains("public void SaveToXmlWorkspace(string workspacePath)", modelCode, StringComparison.Ordinal);
            Assert.Contains("[XmlRoot(", modelCode, StringComparison.Ordinal);
            Assert.Contains("TypedWorkspaceXmlSerializer.Load", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("Signature", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("ModelDefinitionXml", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("XElement", modelCode, StringComparison.Ordinal);
            Assert.DoesNotContain("XDocument", modelCode, StringComparison.Ordinal);
            Assert.Contains("internal static class ArchitectureModelFactory", modelCode, StringComparison.Ordinal);
            Assert.Contains("public static class ArchitectureTooling", toolingCode, StringComparison.Ordinal);
            Assert.Contains("public static ArchitectureModel Load(", toolingCode, StringComparison.Ordinal);
            Assert.Contains("public static Task<ArchitectureModel> LoadAsync(", toolingCode, StringComparison.Ordinal);
            Assert.Contains("namespace Architecture", entityCode, StringComparison.Ordinal);
            Assert.Contains("public sealed class Architecture", entityCode, StringComparison.Ordinal);
        }
        finally
        {
            DeleteDirectoryIfExists(Path.GetDirectoryName(output)!);
        }
    }

    private static void DeleteDirectoryIfExists(string path)
    {
        if (Directory.Exists(path))
        {
            Directory.Delete(path, recursive: true);
        }
    }

    private static string ResolveHeaderWorkspacePath(Workspace workspace)
    {
        return string.IsNullOrWhiteSpace(workspace.WorkspaceRootPath)
            ? ".\\<workspace>"
            : $".\\{Path.GetFileName(Path.GetFullPath(workspace.WorkspaceRootPath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))}";
    }
}

