// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaCli
{
    public sealed class AllowedValue
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string Value { get; set; } = string.Empty;

        public AllowedValue? PreviousValue { get; set; }

        public ValueShape ValueShape { get; set; } = null!;

    }
}
