// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaCli
{
    public sealed class OptionToken
    {
        public string Id { get; set; } = string.Empty;

        public string? IsPrimary { get; set; }

        public string Token { get; set; } = string.Empty;

        public Option Option { get; set; } = null!;

        public OptionToken? PreviousToken { get; set; }

    }
}
