// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaCli
{
    public sealed class ParameterGroupMember
    {
        public string Id { get; set; } = string.Empty;

        public ParameterGroup ParameterGroup { get; set; } = null!;

        public Parameter Parameter { get; set; } = null!;

        public ParameterGroupMember? PreviousMember { get; set; }

    }
}
