// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaCli
{
    public sealed class ParserPolicy
    {
        public string Id { get; set; } = string.Empty;

        public string? AllowsEqualsValueSyntax { get; set; }

        public string? AllowsOptionsAfterPositionals { get; set; }

        public string? AllowsShortOptionClusters { get; set; }

        public string? Description { get; set; }

        public string Name { get; set; } = string.Empty;

        public string? StopParsingToken { get; set; }

        public Application Application { get; set; } = null!;

        public DuplicateOptionBehavior? DuplicateOptionBehavior { get; set; }

        public UnknownTokenBehavior? UnknownTokenBehavior { get; set; }

    }
}
