<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.3.2" />
    <ProjectReference Include="..\..\Meta\Core\Meta.Core.csproj" />
    <ProjectReference Include="..\..\Meta\Surfaces\Meta.Surfaces.csproj" />
    <ProjectReference Include="..\..\Meta\Surfaces.Xml\Meta.Surfaces.Xml.csproj" />
    <ProjectReference Include="..\..\Meta\Integration\Meta.Integration.csproj" />
    <ProjectReference Include="..\..\MetaCli\Core\MetaCli.Core.csproj" />
    <ProjectReference Include="..\..\MetaCli\MetaCli.Model.csproj" />
    <ProjectReference Include="..\..\MetaMesh\MetaMesh.Model.csproj" />
    <ProjectReference Include="..\MetaDocs.Model.csproj" />
  </ItemGroup>

</Project>
