// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Meta.Core.Serialization;

namespace EnterpriseBIPlatform
{
    public sealed partial class EnterpriseBIPlatformModel : IMetaWorkspaceModel<EnterpriseBIPlatformModel>
    {
        public static EnterpriseBIPlatformModel CreateEmpty() => new();

        public List<Cube> CubeList { get; set; } = new();

        public List<Dimension> DimensionList { get; set; } = new();

        public List<Fact> FactList { get; set; } = new();

        public List<Measure> MeasureList { get; set; } = new();

        public List<System> SystemList { get; set; } = new();

        public List<SystemCube> SystemCubeList { get; set; } = new();

        public List<SystemDimension> SystemDimensionList { get; set; } = new();

        public List<SystemFact> SystemFactList { get; set; } = new();

        public List<SystemType> SystemTypeList { get; set; } = new();

        public static EnterpriseBIPlatformModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = false)
        {
            return EnterpriseBIPlatformModelXmlSerializer.Load(workspacePath, searchUpward);
        }

        public static Task<EnterpriseBIPlatformModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            EnterpriseBIPlatformModelXmlSerializer.Save(this, workspacePath);
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }

    internal static class EnterpriseBIPlatformModelXmlSerializer
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        internal static EnterpriseBIPlatformModel Load(string workspacePath, bool searchUpward)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (searchUpward)
            {
                throw new NotSupportedException("Typed workspace loading does not search parent directories. Pass an explicit workspace path.");
            }

            if (HasRuntimeExtendedShape())
            {
                return TypedWorkspaceXmlSerializer.Load<EnterpriseBIPlatformModel>(workspacePath, searchUpward);
            }

            var workspaceRootPath = TypedWorkspaceXmlSerializer.RequireWorkspace<EnterpriseBIPlatformModel>(workspacePath);

            var model = new EnterpriseBIPlatformModel();
            var loadState = new LoadState();
            var relationshipBuffers = new RelationshipBuffers();
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            if (!Directory.Exists(instanceDirectoryPath))
            {
                return model;
            }

            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                LoadShard(model, shardPath, loadState, relationshipBuffers);
            }

            var loadIndexes = new LoadIndexes(model);
            ResolveRelationshipGroup1(loadIndexes, relationshipBuffers);
            return model;
        }

        internal static void Save(EnterpriseBIPlatformModel model, string workspacePath)
        {
            ArgumentNullException.ThrowIfNull(model);
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (HasRuntimeExtendedShape())
            {
                TypedWorkspaceXmlSerializer.Save(model, workspacePath);
                return;
            }

            TypedWorkspaceXmlSerializer.SaveModel(model, workspacePath);

            var saveIndexes = new SaveIndexes(model);

            var workspaceRootPath = Path.GetFullPath(workspacePath);
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            Directory.CreateDirectory(instanceDirectoryPath);
            var expectedShardPaths = BuildExpectedShardPaths(instanceDirectoryPath);
            SaveShardGroup1(model, instanceDirectoryPath, saveIndexes);
            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                if (!expectedShardPaths.Contains(Path.GetFullPath(shardPath)))
                {
                    File.Delete(shardPath);
                }
            }
        }

        private static void SaveShardGroup1(EnterpriseBIPlatformModel model, string instanceDirectoryPath, SaveIndexes saveIndexes)
        {
            model.CubeList ??= new List<Cube>();
            var cubeShardPath = Path.Combine(instanceDirectoryPath, "Cube.xml");
            if (model.CubeList.Count == 0)
            {
                DeleteIfExists(cubeShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(cubeShardPath, SerializeCubeShard(model, saveIndexes));
            }

            model.DimensionList ??= new List<Dimension>();
            var dimensionShardPath = Path.Combine(instanceDirectoryPath, "Dimension.xml");
            if (model.DimensionList.Count == 0)
            {
                DeleteIfExists(dimensionShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(dimensionShardPath, SerializeDimensionShard(model, saveIndexes));
            }

            model.FactList ??= new List<Fact>();
            var factShardPath = Path.Combine(instanceDirectoryPath, "Fact.xml");
            if (model.FactList.Count == 0)
            {
                DeleteIfExists(factShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(factShardPath, SerializeFactShard(model, saveIndexes));
            }

            model.MeasureList ??= new List<Measure>();
            var measureShardPath = Path.Combine(instanceDirectoryPath, "Measure.xml");
            if (model.MeasureList.Count == 0)
            {
                DeleteIfExists(measureShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(measureShardPath, SerializeMeasureShard(model, saveIndexes));
            }

            model.SystemList ??= new List<System>();
            var systemShardPath = Path.Combine(instanceDirectoryPath, "System.xml");
            if (model.SystemList.Count == 0)
            {
                DeleteIfExists(systemShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(systemShardPath, SerializeSystemShard(model, saveIndexes));
            }

            model.SystemCubeList ??= new List<SystemCube>();
            var systemCubeShardPath = Path.Combine(instanceDirectoryPath, "SystemCube.xml");
            if (model.SystemCubeList.Count == 0)
            {
                DeleteIfExists(systemCubeShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(systemCubeShardPath, SerializeSystemCubeShard(model, saveIndexes));
            }

            model.SystemDimensionList ??= new List<SystemDimension>();
            var systemDimensionShardPath = Path.Combine(instanceDirectoryPath, "SystemDimension.xml");
            if (model.SystemDimensionList.Count == 0)
            {
                DeleteIfExists(systemDimensionShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(systemDimensionShardPath, SerializeSystemDimensionShard(model, saveIndexes));
            }

            model.SystemFactList ??= new List<SystemFact>();
            var systemFactShardPath = Path.Combine(instanceDirectoryPath, "SystemFact.xml");
            if (model.SystemFactList.Count == 0)
            {
                DeleteIfExists(systemFactShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(systemFactShardPath, SerializeSystemFactShard(model, saveIndexes));
            }

            model.SystemTypeList ??= new List<SystemType>();
            var systemTypeShardPath = Path.Combine(instanceDirectoryPath, "SystemType.xml");
            if (model.SystemTypeList.Count == 0)
            {
                DeleteIfExists(systemTypeShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(systemTypeShardPath, SerializeSystemTypeShard(model, saveIndexes));
            }

        }

        private static void LoadShard(EnterpriseBIPlatformModel model, string shardPath, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            using var reader = XmlReader.Create(shardPath, new XmlReaderSettings
            {
                IgnoreComments = true,
                IgnoreWhitespace = true,
            });
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element || !string.Equals(reader.LocalName, "EnterpriseBIPlatform", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"Instance XML '{shardPath}' root must be <EnterpriseBIPlatform>.");
            }
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return;
            }
            reader.ReadStartElement("EnterpriseBIPlatform");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "CubeList":
                        LoadCubeList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "DimensionList":
                        LoadDimensionList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "FactList":
                        LoadFactList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "MeasureList":
                        LoadMeasureList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SystemList":
                        LoadSystemList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SystemCubeList":
                        LoadSystemCubeList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SystemDimensionList":
                        LoadSystemDimensionList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SystemFactList":
                        LoadSystemFactList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SystemTypeList":
                        LoadSystemTypeList(model, reader, loadState, relationshipBuffers);
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in '{shardPath}'.");
                }
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static void LoadCubeList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("CubeList");
                return;
            }

            reader.ReadStartElement("CubeList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Cube", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'CubeList'.");
                }
                var row = ReadCube(reader, relationshipBuffers);
                loadState.AddCubeId(row.Id);
                model.CubeList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Cube ReadCube(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Cube();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Cube'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Cube");
                return row;
            }

            reader.ReadStartElement("Cube");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "CubeName":
                        row.CubeName = reader.ReadElementContentAsString();
                        break;
                    case "Purpose":
                        row.Purpose = reader.ReadElementContentAsString();
                        break;
                    case "RefreshMode":
                        row.RefreshMode = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Cube'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeCubeShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <CubeList>\n");
            foreach (var row in model.CubeList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Cube' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Cube' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Cube Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "CubeName", RequireText(row.CubeName, $"Entity 'Cube' row '{row.Id}' is missing required property 'CubeName'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.Purpose))
                {
                    AppendElement(builder, "Purpose", row.Purpose!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.RefreshMode))
                {
                    AppendElement(builder, "RefreshMode", row.RefreshMode!, "      ");
                }
                builder.Append("    </Cube>\n");
            }
            builder.Append("  </CubeList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadDimensionList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("DimensionList");
                return;
            }

            reader.ReadStartElement("DimensionList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Dimension", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'DimensionList'.");
                }
                var row = ReadDimension(reader, relationshipBuffers);
                loadState.AddDimensionId(row.Id);
                model.DimensionList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Dimension ReadDimension(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Dimension();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Dimension'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Dimension");
                return row;
            }

            reader.ReadStartElement("Dimension");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "DimensionName":
                        row.DimensionName = reader.ReadElementContentAsString();
                        break;
                    case "HierarchyCount":
                        row.HierarchyCount = reader.ReadElementContentAsString();
                        break;
                    case "IsConformed":
                        row.IsConformed = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Dimension'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeDimensionShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <DimensionList>\n");
            foreach (var row in model.DimensionList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Dimension' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Dimension' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Dimension Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "DimensionName", RequireText(row.DimensionName, $"Entity 'Dimension' row '{row.Id}' is missing required property 'DimensionName'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.HierarchyCount))
                {
                    AppendElement(builder, "HierarchyCount", row.HierarchyCount!, "      ");
                }
                AppendElement(builder, "IsConformed", RequireText(row.IsConformed, $"Entity 'Dimension' row '{row.Id}' is missing required property 'IsConformed'."), "      ");
                builder.Append("    </Dimension>\n");
            }
            builder.Append("  </DimensionList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadFactList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("FactList");
                return;
            }

            reader.ReadStartElement("FactList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Fact", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'FactList'.");
                }
                var row = ReadFact(reader, relationshipBuffers);
                loadState.AddFactId(row.Id);
                model.FactList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Fact ReadFact(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Fact();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Fact'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Fact");
                return row;
            }

            reader.ReadStartElement("Fact");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "BusinessArea":
                        row.BusinessArea = reader.ReadElementContentAsString();
                        break;
                    case "FactName":
                        row.FactName = reader.ReadElementContentAsString();
                        break;
                    case "Grain":
                        row.Grain = reader.ReadElementContentAsString();
                        break;
                    case "MeasureCount":
                        row.MeasureCount = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Fact'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeFactShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <FactList>\n");
            foreach (var row in model.FactList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Fact' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Fact' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Fact Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.BusinessArea))
                {
                    AppendElement(builder, "BusinessArea", row.BusinessArea!, "      ");
                }
                AppendElement(builder, "FactName", RequireText(row.FactName, $"Entity 'Fact' row '{row.Id}' is missing required property 'FactName'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.Grain))
                {
                    AppendElement(builder, "Grain", row.Grain!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.MeasureCount))
                {
                    AppendElement(builder, "MeasureCount", row.MeasureCount!, "      ");
                }
                builder.Append("    </Fact>\n");
            }
            builder.Append("  </FactList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadMeasureList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("MeasureList");
                return;
            }

            reader.ReadStartElement("MeasureList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Measure", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'MeasureList'.");
                }
                var row = ReadMeasure(reader, relationshipBuffers);
                loadState.AddMeasureId(row.Id);
                model.MeasureList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Measure ReadMeasure(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Measure();
            var relationships = new MeasureRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "CubeId":
                            relationships.CubeId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Measure'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Measure");
                (relationshipBuffers.MeasureRelationships ??= new List<MeasureRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("Measure");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "MDX":
                        row.MDX = reader.ReadElementContentAsString();
                        break;
                    case "MeasureName":
                        row.MeasureName = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Measure'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.MeasureRelationships ??= new List<MeasureRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeMeasureShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <MeasureList>\n");
            foreach (var row in model.MeasureList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Measure' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Measure' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Measure Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var cubeId = RequireIdentity(row.Cube?.Id, $"Relationship 'Measure.CubeId' on row 'Measure:{row.Id}' is empty.");
                if (!saveIndexes.CubeListById.TryGetValue(cubeId, out var cubeCanonical) || !ReferenceEquals(cubeCanonical, row.Cube))
                {
                    throw new InvalidOperationException($"Relationship 'Measure.CubeId' on row 'Measure:{row.Id}' references an object that is not the canonical row for Id '{cubeId}'.");
                }
                builder.Append(' ');
                builder.Append("CubeId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, cubeId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.MDX))
                {
                    AppendElement(builder, "MDX", row.MDX!, "      ");
                }
                AppendElement(builder, "MeasureName", RequireText(row.MeasureName, $"Entity 'Measure' row '{row.Id}' is missing required property 'MeasureName'."), "      ");
                builder.Append("    </Measure>\n");
            }
            builder.Append("  </MeasureList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSystemList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemList");
                return;
            }

            reader.ReadStartElement("SystemList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "System", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SystemList'.");
                }
                var row = ReadSystem(reader, relationshipBuffers);
                loadState.AddSystemId(row.Id);
                model.SystemList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static System ReadSystem(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new System();
            var relationships = new SystemRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "SystemTypeId":
                            relationships.SystemTypeId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'System'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("System");
                (relationshipBuffers.SystemRelationships ??= new List<SystemRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("System");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "DeploymentDate":
                        row.DeploymentDate = reader.ReadElementContentAsString();
                        break;
                    case "SystemName":
                        row.SystemName = reader.ReadElementContentAsString();
                        break;
                    case "Version":
                        row.Version = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'System'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.SystemRelationships ??= new List<SystemRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeSystemShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <SystemList>\n");
            foreach (var row in model.SystemList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'System' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'System' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <System Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var systemTypeId = RequireIdentity(row.SystemType?.Id, $"Relationship 'System.SystemTypeId' on row 'System:{row.Id}' is empty.");
                if (!saveIndexes.SystemTypeListById.TryGetValue(systemTypeId, out var systemTypeCanonical) || !ReferenceEquals(systemTypeCanonical, row.SystemType))
                {
                    throw new InvalidOperationException($"Relationship 'System.SystemTypeId' on row 'System:{row.Id}' references an object that is not the canonical row for Id '{systemTypeId}'.");
                }
                builder.Append(' ');
                builder.Append("SystemTypeId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, systemTypeId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.DeploymentDate))
                {
                    AppendElement(builder, "DeploymentDate", row.DeploymentDate!, "      ");
                }
                AppendElement(builder, "SystemName", RequireText(row.SystemName, $"Entity 'System' row '{row.Id}' is missing required property 'SystemName'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.Version))
                {
                    AppendElement(builder, "Version", row.Version!, "      ");
                }
                builder.Append("    </System>\n");
            }
            builder.Append("  </SystemList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSystemCubeList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemCubeList");
                return;
            }

            reader.ReadStartElement("SystemCubeList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "SystemCube", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SystemCubeList'.");
                }
                var row = ReadSystemCube(reader, relationshipBuffers);
                loadState.AddSystemCubeId(row.Id);
                model.SystemCubeList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static SystemCube ReadSystemCube(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new SystemCube();
            var relationships = new SystemCubeRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "CubeId":
                            relationships.CubeId = reader.Value;
                            break;
                        case "SystemId":
                            relationships.SystemId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'SystemCube'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemCube");
                (relationshipBuffers.SystemCubeRelationships ??= new List<SystemCubeRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("SystemCube");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "ProcessingMode":
                        row.ProcessingMode = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'SystemCube'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.SystemCubeRelationships ??= new List<SystemCubeRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeSystemCubeShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <SystemCubeList>\n");
            foreach (var row in model.SystemCubeList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'SystemCube' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'SystemCube' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <SystemCube Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var cubeId = RequireIdentity(row.Cube?.Id, $"Relationship 'SystemCube.CubeId' on row 'SystemCube:{row.Id}' is empty.");
                if (!saveIndexes.CubeListById.TryGetValue(cubeId, out var cubeCanonical) || !ReferenceEquals(cubeCanonical, row.Cube))
                {
                    throw new InvalidOperationException($"Relationship 'SystemCube.CubeId' on row 'SystemCube:{row.Id}' references an object that is not the canonical row for Id '{cubeId}'.");
                }
                builder.Append(' ');
                builder.Append("CubeId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, cubeId);
                builder.Append('"');
                var systemId = RequireIdentity(row.System?.Id, $"Relationship 'SystemCube.SystemId' on row 'SystemCube:{row.Id}' is empty.");
                if (!saveIndexes.SystemListById.TryGetValue(systemId, out var systemCanonical) || !ReferenceEquals(systemCanonical, row.System))
                {
                    throw new InvalidOperationException($"Relationship 'SystemCube.SystemId' on row 'SystemCube:{row.Id}' references an object that is not the canonical row for Id '{systemId}'.");
                }
                builder.Append(' ');
                builder.Append("SystemId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, systemId);
                builder.Append('"');
                var openingTagEndIndex = builder.Length;
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.ProcessingMode))
                {
                    AppendElement(builder, "ProcessingMode", row.ProcessingMode!, "      ");
                }
                AppendClosingElementOrSelfClose(builder, openingTagEndIndex, "    </SystemCube>\n");
            }
            builder.Append("  </SystemCubeList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSystemDimensionList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemDimensionList");
                return;
            }

            reader.ReadStartElement("SystemDimensionList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "SystemDimension", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SystemDimensionList'.");
                }
                var row = ReadSystemDimension(reader, relationshipBuffers);
                loadState.AddSystemDimensionId(row.Id);
                model.SystemDimensionList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static SystemDimension ReadSystemDimension(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new SystemDimension();
            var relationships = new SystemDimensionRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "DimensionId":
                            relationships.DimensionId = reader.Value;
                            break;
                        case "SystemId":
                            relationships.SystemId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'SystemDimension'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemDimension");
                (relationshipBuffers.SystemDimensionRelationships ??= new List<SystemDimensionRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("SystemDimension");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "ConformanceLevel":
                        row.ConformanceLevel = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'SystemDimension'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.SystemDimensionRelationships ??= new List<SystemDimensionRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeSystemDimensionShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <SystemDimensionList>\n");
            foreach (var row in model.SystemDimensionList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'SystemDimension' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'SystemDimension' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <SystemDimension Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var dimensionId = RequireIdentity(row.Dimension?.Id, $"Relationship 'SystemDimension.DimensionId' on row 'SystemDimension:{row.Id}' is empty.");
                if (!saveIndexes.DimensionListById.TryGetValue(dimensionId, out var dimensionCanonical) || !ReferenceEquals(dimensionCanonical, row.Dimension))
                {
                    throw new InvalidOperationException($"Relationship 'SystemDimension.DimensionId' on row 'SystemDimension:{row.Id}' references an object that is not the canonical row for Id '{dimensionId}'.");
                }
                builder.Append(' ');
                builder.Append("DimensionId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, dimensionId);
                builder.Append('"');
                var systemId = RequireIdentity(row.System?.Id, $"Relationship 'SystemDimension.SystemId' on row 'SystemDimension:{row.Id}' is empty.");
                if (!saveIndexes.SystemListById.TryGetValue(systemId, out var systemCanonical) || !ReferenceEquals(systemCanonical, row.System))
                {
                    throw new InvalidOperationException($"Relationship 'SystemDimension.SystemId' on row 'SystemDimension:{row.Id}' references an object that is not the canonical row for Id '{systemId}'.");
                }
                builder.Append(' ');
                builder.Append("SystemId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, systemId);
                builder.Append('"');
                var openingTagEndIndex = builder.Length;
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.ConformanceLevel))
                {
                    AppendElement(builder, "ConformanceLevel", row.ConformanceLevel!, "      ");
                }
                AppendClosingElementOrSelfClose(builder, openingTagEndIndex, "    </SystemDimension>\n");
            }
            builder.Append("  </SystemDimensionList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSystemFactList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemFactList");
                return;
            }

            reader.ReadStartElement("SystemFactList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "SystemFact", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SystemFactList'.");
                }
                var row = ReadSystemFact(reader, relationshipBuffers);
                loadState.AddSystemFactId(row.Id);
                model.SystemFactList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static SystemFact ReadSystemFact(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new SystemFact();
            var relationships = new SystemFactRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FactId":
                            relationships.FactId = reader.Value;
                            break;
                        case "SystemId":
                            relationships.SystemId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'SystemFact'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemFact");
                (relationshipBuffers.SystemFactRelationships ??= new List<SystemFactRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("SystemFact");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "LoadPattern":
                        row.LoadPattern = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'SystemFact'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.SystemFactRelationships ??= new List<SystemFactRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeSystemFactShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <SystemFactList>\n");
            foreach (var row in model.SystemFactList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'SystemFact' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'SystemFact' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <SystemFact Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var factId = RequireIdentity(row.Fact?.Id, $"Relationship 'SystemFact.FactId' on row 'SystemFact:{row.Id}' is empty.");
                if (!saveIndexes.FactListById.TryGetValue(factId, out var factCanonical) || !ReferenceEquals(factCanonical, row.Fact))
                {
                    throw new InvalidOperationException($"Relationship 'SystemFact.FactId' on row 'SystemFact:{row.Id}' references an object that is not the canonical row for Id '{factId}'.");
                }
                builder.Append(' ');
                builder.Append("FactId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, factId);
                builder.Append('"');
                var systemId = RequireIdentity(row.System?.Id, $"Relationship 'SystemFact.SystemId' on row 'SystemFact:{row.Id}' is empty.");
                if (!saveIndexes.SystemListById.TryGetValue(systemId, out var systemCanonical) || !ReferenceEquals(systemCanonical, row.System))
                {
                    throw new InvalidOperationException($"Relationship 'SystemFact.SystemId' on row 'SystemFact:{row.Id}' references an object that is not the canonical row for Id '{systemId}'.");
                }
                builder.Append(' ');
                builder.Append("SystemId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, systemId);
                builder.Append('"');
                var openingTagEndIndex = builder.Length;
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.LoadPattern))
                {
                    AppendElement(builder, "LoadPattern", row.LoadPattern!, "      ");
                }
                AppendClosingElementOrSelfClose(builder, openingTagEndIndex, "    </SystemFact>\n");
            }
            builder.Append("  </SystemFactList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSystemTypeList(EnterpriseBIPlatformModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemTypeList");
                return;
            }

            reader.ReadStartElement("SystemTypeList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "SystemType", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SystemTypeList'.");
                }
                var row = ReadSystemType(reader, relationshipBuffers);
                loadState.AddSystemTypeId(row.Id);
                model.SystemTypeList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static SystemType ReadSystemType(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new SystemType();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'SystemType'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SystemType");
                return row;
            }

            reader.ReadStartElement("SystemType");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "TypeName":
                        row.TypeName = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'SystemType'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeSystemTypeShard(EnterpriseBIPlatformModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<EnterpriseBIPlatform>\n");
            builder.Append("  <SystemTypeList>\n");
            foreach (var row in model.SystemTypeList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'SystemType' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'SystemType' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <SystemType Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "TypeName", RequireText(row.TypeName, $"Entity 'SystemType' row '{row.Id}' is missing required property 'TypeName'."), "      ");
                builder.Append("    </SystemType>\n");
            }
            builder.Append("  </SystemTypeList>\n");
            builder.Append("</EnterpriseBIPlatform>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private sealed class MeasureRelationships
        {
            public Measure Row { get; set; } = null!;
            public string CubeId { get; set; } = string.Empty;
        }

        private sealed class SystemRelationships
        {
            public System Row { get; set; } = null!;
            public string SystemTypeId { get; set; } = string.Empty;
        }

        private sealed class SystemCubeRelationships
        {
            public SystemCube Row { get; set; } = null!;
            public string CubeId { get; set; } = string.Empty;
            public string SystemId { get; set; } = string.Empty;
        }

        private sealed class SystemDimensionRelationships
        {
            public SystemDimension Row { get; set; } = null!;
            public string DimensionId { get; set; } = string.Empty;
            public string SystemId { get; set; } = string.Empty;
        }

        private sealed class SystemFactRelationships
        {
            public SystemFact Row { get; set; } = null!;
            public string FactId { get; set; } = string.Empty;
            public string SystemId { get; set; } = string.Empty;
        }

        private sealed class RelationshipBuffers
        {
            public List<MeasureRelationships>? MeasureRelationships { get; set; }
            public List<SystemRelationships>? SystemRelationships { get; set; }
            public List<SystemCubeRelationships>? SystemCubeRelationships { get; set; }
            public List<SystemDimensionRelationships>? SystemDimensionRelationships { get; set; }
            public List<SystemFactRelationships>? SystemFactRelationships { get; set; }
        }

        private static void ResolveRelationshipGroup1(LoadIndexes loadIndexes, RelationshipBuffers relationshipBuffers)
        {
            foreach (var relationship in relationshipBuffers.MeasureRelationships ?? Enumerable.Empty<MeasureRelationships>())
            {
                relationship.Row.Cube = RequireTarget(
                    loadIndexes.CubeListById,
                    relationship.CubeId,
                    "Measure",
                    relationship.Row.Id,
                    "CubeId");
            }

            foreach (var relationship in relationshipBuffers.SystemRelationships ?? Enumerable.Empty<SystemRelationships>())
            {
                relationship.Row.SystemType = RequireTarget(
                    loadIndexes.SystemTypeListById,
                    relationship.SystemTypeId,
                    "System",
                    relationship.Row.Id,
                    "SystemTypeId");
            }

            foreach (var relationship in relationshipBuffers.SystemCubeRelationships ?? Enumerable.Empty<SystemCubeRelationships>())
            {
                relationship.Row.Cube = RequireTarget(
                    loadIndexes.CubeListById,
                    relationship.CubeId,
                    "SystemCube",
                    relationship.Row.Id,
                    "CubeId");
            }

            foreach (var relationship in relationshipBuffers.SystemCubeRelationships ?? Enumerable.Empty<SystemCubeRelationships>())
            {
                relationship.Row.System = RequireTarget(
                    loadIndexes.SystemListById,
                    relationship.SystemId,
                    "SystemCube",
                    relationship.Row.Id,
                    "SystemId");
            }

            foreach (var relationship in relationshipBuffers.SystemDimensionRelationships ?? Enumerable.Empty<SystemDimensionRelationships>())
            {
                relationship.Row.Dimension = RequireTarget(
                    loadIndexes.DimensionListById,
                    relationship.DimensionId,
                    "SystemDimension",
                    relationship.Row.Id,
                    "DimensionId");
            }

            foreach (var relationship in relationshipBuffers.SystemDimensionRelationships ?? Enumerable.Empty<SystemDimensionRelationships>())
            {
                relationship.Row.System = RequireTarget(
                    loadIndexes.SystemListById,
                    relationship.SystemId,
                    "SystemDimension",
                    relationship.Row.Id,
                    "SystemId");
            }

            foreach (var relationship in relationshipBuffers.SystemFactRelationships ?? Enumerable.Empty<SystemFactRelationships>())
            {
                relationship.Row.Fact = RequireTarget(
                    loadIndexes.FactListById,
                    relationship.FactId,
                    "SystemFact",
                    relationship.Row.Id,
                    "FactId");
            }

            foreach (var relationship in relationshipBuffers.SystemFactRelationships ?? Enumerable.Empty<SystemFactRelationships>())
            {
                relationship.Row.System = RequireTarget(
                    loadIndexes.SystemListById,
                    relationship.SystemId,
                    "SystemFact",
                    relationship.Row.Id,
                    "SystemId");
            }

        }

        private static readonly string[] ShardFileNames =
        {
            "Cube.xml",
            "Dimension.xml",
            "Fact.xml",
            "Measure.xml",
            "System.xml",
            "SystemCube.xml",
            "SystemDimension.xml",
            "SystemFact.xml",
            "SystemType.xml",
        };

        private static HashSet<string> BuildExpectedShardPaths(string instanceDirectoryPath)
        {
            var expectedShardPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var shardFileName in ShardFileNames)
            {
                expectedShardPaths.Add(Path.GetFullPath(Path.Combine(instanceDirectoryPath, shardFileName)));
            }

            return expectedShardPaths;
        }

        private sealed class LoadState
        {
            private HashSet<string>? cubeIds;

            public void AddCubeId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Cube' contains a row with empty Id.");
                cubeIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!cubeIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Cube' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? dimensionIds;

            public void AddDimensionId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Dimension' contains a row with empty Id.");
                dimensionIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!dimensionIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Dimension' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? factIds;

            public void AddFactId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Fact' contains a row with empty Id.");
                factIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!factIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Fact' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? measureIds;

            public void AddMeasureId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Measure' contains a row with empty Id.");
                measureIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!measureIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Measure' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? systemIds;

            public void AddSystemId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'System' contains a row with empty Id.");
                systemIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!systemIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'System' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? systemCubeIds;

            public void AddSystemCubeId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'SystemCube' contains a row with empty Id.");
                systemCubeIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!systemCubeIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'SystemCube' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? systemDimensionIds;

            public void AddSystemDimensionId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'SystemDimension' contains a row with empty Id.");
                systemDimensionIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!systemDimensionIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'SystemDimension' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? systemFactIds;

            public void AddSystemFactId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'SystemFact' contains a row with empty Id.");
                systemFactIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!systemFactIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'SystemFact' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? systemTypeIds;

            public void AddSystemTypeId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'SystemType' contains a row with empty Id.");
                systemTypeIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!systemTypeIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'SystemType' contains duplicate Id '{normalizedId}'.");
                }
            }

        }

        private sealed class LoadIndexes
        {
            private readonly EnterpriseBIPlatformModel model;

            public LoadIndexes(EnterpriseBIPlatformModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Cube>? cubeListById;

            public Dictionary<string, Cube> CubeListById => cubeListById ??= BuildById(model.CubeList, row => row.Id, "Cube");

            private Dictionary<string, Dimension>? dimensionListById;

            public Dictionary<string, Dimension> DimensionListById => dimensionListById ??= BuildById(model.DimensionList, row => row.Id, "Dimension");

            private Dictionary<string, Fact>? factListById;

            public Dictionary<string, Fact> FactListById => factListById ??= BuildById(model.FactList, row => row.Id, "Fact");

            private Dictionary<string, Measure>? measureListById;

            public Dictionary<string, Measure> MeasureListById => measureListById ??= BuildById(model.MeasureList, row => row.Id, "Measure");

            private Dictionary<string, System>? systemListById;

            public Dictionary<string, System> SystemListById => systemListById ??= BuildById(model.SystemList, row => row.Id, "System");

            private Dictionary<string, SystemCube>? systemCubeListById;

            public Dictionary<string, SystemCube> SystemCubeListById => systemCubeListById ??= BuildById(model.SystemCubeList, row => row.Id, "SystemCube");

            private Dictionary<string, SystemDimension>? systemDimensionListById;

            public Dictionary<string, SystemDimension> SystemDimensionListById => systemDimensionListById ??= BuildById(model.SystemDimensionList, row => row.Id, "SystemDimension");

            private Dictionary<string, SystemFact>? systemFactListById;

            public Dictionary<string, SystemFact> SystemFactListById => systemFactListById ??= BuildById(model.SystemFactList, row => row.Id, "SystemFact");

            private Dictionary<string, SystemType>? systemTypeListById;

            public Dictionary<string, SystemType> SystemTypeListById => systemTypeListById ??= BuildById(model.SystemTypeList, row => row.Id, "SystemType");

        }

        private sealed class SaveIndexes
        {
            private readonly EnterpriseBIPlatformModel model;

            public SaveIndexes(EnterpriseBIPlatformModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Cube>? cubeListById;

            public Dictionary<string, Cube> CubeListById => cubeListById ??= BuildById(model.CubeList, row => row.Id, "Cube");

            private Dictionary<string, Dimension>? dimensionListById;

            public Dictionary<string, Dimension> DimensionListById => dimensionListById ??= BuildById(model.DimensionList, row => row.Id, "Dimension");

            private Dictionary<string, Fact>? factListById;

            public Dictionary<string, Fact> FactListById => factListById ??= BuildById(model.FactList, row => row.Id, "Fact");

            private Dictionary<string, Measure>? measureListById;

            public Dictionary<string, Measure> MeasureListById => measureListById ??= BuildById(model.MeasureList, row => row.Id, "Measure");

            private Dictionary<string, System>? systemListById;

            public Dictionary<string, System> SystemListById => systemListById ??= BuildById(model.SystemList, row => row.Id, "System");

            private Dictionary<string, SystemCube>? systemCubeListById;

            public Dictionary<string, SystemCube> SystemCubeListById => systemCubeListById ??= BuildById(model.SystemCubeList, row => row.Id, "SystemCube");

            private Dictionary<string, SystemDimension>? systemDimensionListById;

            public Dictionary<string, SystemDimension> SystemDimensionListById => systemDimensionListById ??= BuildById(model.SystemDimensionList, row => row.Id, "SystemDimension");

            private Dictionary<string, SystemFact>? systemFactListById;

            public Dictionary<string, SystemFact> SystemFactListById => systemFactListById ??= BuildById(model.SystemFactList, row => row.Id, "SystemFact");

            private Dictionary<string, SystemType>? systemTypeListById;

            public Dictionary<string, SystemType> SystemTypeListById => systemTypeListById ??= BuildById(model.SystemTypeList, row => row.Id, "SystemType");

        }

        private static readonly Lazy<bool> RuntimeExtendedShape = new(DetectRuntimeExtendedShape);

        private static bool HasRuntimeExtendedShape()
        {
            return RuntimeExtendedShape.Value;
        }

        private static bool DetectRuntimeExtendedShape()
        {
            if (HasRuntimeExtendedEntityShapeGroup1())
            {
                return true;
            }

            return HasUnexpectedModelLists();
        }

        private static bool HasRuntimeExtendedEntityShapeGroup1()
        {
            if (HasUnexpectedProperties(typeof(Cube),
                "Id",
                "CubeName",
                "Purpose",
                "RefreshMode"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Dimension),
                "Id",
                "DimensionName",
                "HierarchyCount",
                "IsConformed"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Fact),
                "Id",
                "BusinessArea",
                "FactName",
                "Grain",
                "MeasureCount"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Measure),
                "Id",
                "MDX",
                "MeasureName",
                "Cube"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(System),
                "Id",
                "DeploymentDate",
                "SystemName",
                "Version",
                "SystemType"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(SystemCube),
                "Id",
                "ProcessingMode",
                "Cube",
                "System"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(SystemDimension),
                "Id",
                "ConformanceLevel",
                "Dimension",
                "System"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(SystemFact),
                "Id",
                "LoadPattern",
                "Fact",
                "System"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(SystemType),
                "Id",
                "Description",
                "TypeName"))
            {
                return true;
            }

            return false;
        }

        private static bool HasUnexpectedModelLists()
        {
            var knownLists = new HashSet<string>(StringComparer.Ordinal)
            {
                "CubeList",
                "DimensionList",
                "FactList",
                "MeasureList",
                "SystemList",
                "SystemCubeList",
                "SystemDimensionList",
                "SystemFactList",
                "SystemTypeList",
            };
            return typeof(EnterpriseBIPlatformModel).GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Any(property =>
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(List<>) &&
                    !knownLists.Contains(property.Name));
        }

        private static bool HasUnexpectedProperties(Type type, params string[] knownProperties)
        {
            return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanRead && property.CanWrite && property.GetIndexParameters().Length == 0)
                .Any(property => !knownProperties.Contains(property.Name, StringComparer.Ordinal));
        }

        private static Dictionary<string, T> BuildById<T>(IEnumerable<T> rows, Func<T, string> getId, string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }
            return rowsById;
        }

        private static T RequireTarget<T>(Dictionary<string, T> rowsById, string targetId, string sourceEntityName, string sourceId, string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidDataException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }
            return target;
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var identity = value ?? string.Empty;
            if (string.IsNullOrWhiteSpace(identity))
            {
                throw new InvalidOperationException(errorMessage);
            }
            if (!string.Equals(identity, identity.Trim(), StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"{errorMessage} Identity cannot contain leading or trailing whitespace.");
            }
            if (identity.Length > 450)
            {
                throw new InvalidOperationException($"{errorMessage} Identity cannot exceed 450 characters.");
            }
            return identity;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return value;
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string indent)
        {
            builder.Append(indent);
            builder.Append('<');
            builder.Append(name);
            builder.Append('>');
            AppendXmlText(builder, value);
            builder.Append("</");
            builder.Append(name);
            builder.Append(">\n");
        }

        private static void AppendClosingElementOrSelfClose(StringBuilder builder, int openingTagEndIndex, string closingElement)
        {
            if (builder.Length == openingTagEndIndex + 2)
            {
                builder.Length = openingTagEndIndex;
                builder.Append(" />\n");
                return;
            }

            builder.Append(closingElement);
        }

        private static void AppendXmlAttribute(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    case '"': builder.Append("&quot;"); break;
                    case '\'': builder.Append("&apos;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static void AppendXmlText(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static bool IsNamespaceDeclaration(XmlReader reader)
        {
            return string.Equals(reader.Prefix, "xmlns", StringComparison.Ordinal) ||
                   string.Equals(reader.LocalName, "xmlns", StringComparison.Ordinal);
        }

        private static void DeleteIfExists(string path)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

    }

}
