// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class Fact
    {
        public string Id { get; set; } = string.Empty;

        public string? BusinessArea { get; set; }

        public string FactName { get; set; } = string.Empty;

        public string? Grain { get; set; }

        public string? MeasureCount { get; set; }

    }
}
