// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class Measure
    {
        public string Id { get; set; } = string.Empty;

        public string? MDX { get; set; }

        public string MeasureName { get; set; } = string.Empty;

        public Cube Cube { get; set; } = null!;

    }
}
