// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class SystemType
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string TypeName { get; set; } = string.Empty;

    }
}
