// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class SystemCube
    {
        public string Id { get; set; } = string.Empty;

        public string? ProcessingMode { get; set; }

        public Cube Cube { get; set; } = null!;

        public System System { get; set; } = null!;

    }
}
