// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class System
    {
        public string Id { get; set; } = string.Empty;

        public string? DeploymentDate { get; set; }

        public string SystemName { get; set; } = string.Empty;

        public string? Version { get; set; }

        public SystemType SystemType { get; set; } = null!;

    }
}
