// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace EnterpriseBIPlatform
{
    public sealed class SystemDimension
    {
        public string Id { get; set; } = string.Empty;

        public string? ConformanceLevel { get; set; }

        public Dimension Dimension { get; set; } = null!;

        public System System { get; set; } = null!;

    }
}
