// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class MeshSuggestion
    {
        public string Id { get; set; } = string.Empty;

        public string Message { get; set; } = string.Empty;

        public string Severity { get; set; } = string.Empty;

        public string? SuggestedHandle { get; set; }

        public string? SuggestedLifecycle { get; set; }

        public string? SuggestedPath { get; set; }

        public string? SuggestedWorkspaceKind { get; set; }

        public string SuggestionKind { get; set; } = string.Empty;

        public string? WorkspaceHandle { get; set; }

        public Mesh Mesh { get; set; } = null!;

        public WorkspaceInstance? WorkspaceInstance { get; set; }

    }
}
