// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Meta.Core.Serialization;

namespace MetaMesh
{
    public sealed partial class MetaMeshModel : IMetaWorkspaceModel<MetaMeshModel>
    {
        public static MetaMeshModel CreateEmpty() => new();

        public List<CSharpWorkspace> CSharpWorkspaceList { get; set; } = new();

        public List<Mesh> MeshList { get; set; } = new();

        public List<Operation> OperationList { get; set; } = new();

        public List<OperationStep> OperationStepList { get; set; } = new();

        public List<SqlWorkspace> SqlWorkspaceList { get; set; } = new();

        public List<Workspace> WorkspaceList { get; set; } = new();

        public List<XmlWorkspace> XmlWorkspaceList { get; set; } = new();

        public static MetaMeshModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaMeshModelXmlSerializer.Load(workspacePath, searchUpward);
        }

        public static Task<MetaMeshModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaMeshModelXmlSerializer.Save(this, workspacePath);
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }

    internal static class MetaMeshModelXmlSerializer
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        internal static MetaMeshModel Load(string workspacePath, bool searchUpward)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (searchUpward)
            {
                throw new NotSupportedException("Typed workspace loading does not search parent directories. Pass an explicit workspace path.");
            }

            if (HasRuntimeExtendedShape())
            {
                return TypedWorkspaceXmlSerializer.Load<MetaMeshModel>(workspacePath, searchUpward);
            }

            var workspaceRootPath = TypedWorkspaceXmlSerializer.RequireWorkspace<MetaMeshModel>(workspacePath);

            var model = new MetaMeshModel();
            var loadState = new LoadState();
            var relationshipBuffers = new RelationshipBuffers();
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            if (!Directory.Exists(instanceDirectoryPath))
            {
                return model;
            }

            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                LoadShard(model, shardPath, loadState, relationshipBuffers);
            }

            var loadIndexes = new LoadIndexes(model);
            ResolveRelationshipGroup1(loadIndexes, relationshipBuffers);
            return model;
        }

        internal static void Save(MetaMeshModel model, string workspacePath)
        {
            ArgumentNullException.ThrowIfNull(model);
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (HasRuntimeExtendedShape())
            {
                TypedWorkspaceXmlSerializer.Save(model, workspacePath);
                return;
            }

            TypedWorkspaceXmlSerializer.SaveModel(model, workspacePath);

            var saveIndexes = new SaveIndexes(model);

            var workspaceRootPath = Path.GetFullPath(workspacePath);
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            Directory.CreateDirectory(instanceDirectoryPath);
            var expectedShardPaths = BuildExpectedShardPaths(instanceDirectoryPath);
            SaveShardGroup1(model, instanceDirectoryPath, saveIndexes);
            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                if (!expectedShardPaths.Contains(Path.GetFullPath(shardPath)))
                {
                    File.Delete(shardPath);
                }
            }
        }

        private static void SaveShardGroup1(MetaMeshModel model, string instanceDirectoryPath, SaveIndexes saveIndexes)
        {
            model.CSharpWorkspaceList ??= new List<CSharpWorkspace>();
            var cSharpWorkspaceShardPath = Path.Combine(instanceDirectoryPath, "CSharpWorkspace.xml");
            if (model.CSharpWorkspaceList.Count == 0)
            {
                DeleteIfExists(cSharpWorkspaceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(cSharpWorkspaceShardPath, SerializeCSharpWorkspaceShard(model, saveIndexes));
            }

            model.MeshList ??= new List<Mesh>();
            var meshShardPath = Path.Combine(instanceDirectoryPath, "Mesh.xml");
            if (model.MeshList.Count == 0)
            {
                DeleteIfExists(meshShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(meshShardPath, SerializeMeshShard(model, saveIndexes));
            }

            model.OperationList ??= new List<Operation>();
            var operationShardPath = Path.Combine(instanceDirectoryPath, "Operation.xml");
            if (model.OperationList.Count == 0)
            {
                DeleteIfExists(operationShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(operationShardPath, SerializeOperationShard(model, saveIndexes));
            }

            model.OperationStepList ??= new List<OperationStep>();
            var operationStepShardPath = Path.Combine(instanceDirectoryPath, "OperationStep.xml");
            if (model.OperationStepList.Count == 0)
            {
                DeleteIfExists(operationStepShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(operationStepShardPath, SerializeOperationStepShard(model, saveIndexes));
            }

            model.SqlWorkspaceList ??= new List<SqlWorkspace>();
            var sqlWorkspaceShardPath = Path.Combine(instanceDirectoryPath, "SqlWorkspace.xml");
            if (model.SqlWorkspaceList.Count == 0)
            {
                DeleteIfExists(sqlWorkspaceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(sqlWorkspaceShardPath, SerializeSqlWorkspaceShard(model, saveIndexes));
            }

            model.WorkspaceList ??= new List<Workspace>();
            var workspaceShardPath = Path.Combine(instanceDirectoryPath, "Workspace.xml");
            if (model.WorkspaceList.Count == 0)
            {
                DeleteIfExists(workspaceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(workspaceShardPath, SerializeWorkspaceShard(model, saveIndexes));
            }

            model.XmlWorkspaceList ??= new List<XmlWorkspace>();
            var xmlWorkspaceShardPath = Path.Combine(instanceDirectoryPath, "XmlWorkspace.xml");
            if (model.XmlWorkspaceList.Count == 0)
            {
                DeleteIfExists(xmlWorkspaceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(xmlWorkspaceShardPath, SerializeXmlWorkspaceShard(model, saveIndexes));
            }

        }

        private static void LoadShard(MetaMeshModel model, string shardPath, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            using var reader = XmlReader.Create(shardPath, new XmlReaderSettings
            {
                IgnoreComments = true,
                IgnoreWhitespace = true,
            });
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element || !string.Equals(reader.LocalName, "MetaMesh", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"Instance XML '{shardPath}' root must be <MetaMesh>.");
            }
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return;
            }
            reader.ReadStartElement("MetaMesh");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "CSharpWorkspaceList":
                        LoadCSharpWorkspaceList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "MeshList":
                        LoadMeshList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "OperationList":
                        LoadOperationList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "OperationStepList":
                        LoadOperationStepList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "SqlWorkspaceList":
                        LoadSqlWorkspaceList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "WorkspaceList":
                        LoadWorkspaceList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "XmlWorkspaceList":
                        LoadXmlWorkspaceList(model, reader, loadState, relationshipBuffers);
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in '{shardPath}'.");
                }
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static void LoadCSharpWorkspaceList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("CSharpWorkspaceList");
                return;
            }

            reader.ReadStartElement("CSharpWorkspaceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "CSharpWorkspace", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'CSharpWorkspaceList'.");
                }
                var row = ReadCSharpWorkspace(reader, relationshipBuffers);
                loadState.AddCSharpWorkspaceId(row.Id);
                model.CSharpWorkspaceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static CSharpWorkspace ReadCSharpWorkspace(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new CSharpWorkspace();
            var relationships = new CSharpWorkspaceRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "WorkspaceId":
                            relationships.WorkspaceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'CSharpWorkspace'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("CSharpWorkspace");
                (relationshipBuffers.CSharpWorkspaceRelationships ??= new List<CSharpWorkspaceRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("CSharpWorkspace");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Path":
                        row.Path = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'CSharpWorkspace'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.CSharpWorkspaceRelationships ??= new List<CSharpWorkspaceRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeCSharpWorkspaceShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <CSharpWorkspaceList>\n");
            foreach (var row in model.CSharpWorkspaceList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'CSharpWorkspace' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'CSharpWorkspace' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <CSharpWorkspace Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var workspaceId = RequireIdentity(row.Workspace?.Id, $"Relationship 'CSharpWorkspace.WorkspaceId' on row 'CSharpWorkspace:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceListById.TryGetValue(workspaceId, out var workspaceCanonical) || !ReferenceEquals(workspaceCanonical, row.Workspace))
                {
                    throw new InvalidOperationException($"Relationship 'CSharpWorkspace.WorkspaceId' on row 'CSharpWorkspace:{row.Id}' references an object that is not the canonical row for Id '{workspaceId}'.");
                }
                builder.Append(' ');
                builder.Append("WorkspaceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, workspaceId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Path", RequireText(row.Path, $"Entity 'CSharpWorkspace' row '{row.Id}' is missing required property 'Path'."), "      ");
                builder.Append("    </CSharpWorkspace>\n");
            }
            builder.Append("  </CSharpWorkspaceList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadMeshList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("MeshList");
                return;
            }

            reader.ReadStartElement("MeshList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Mesh", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'MeshList'.");
                }
                var row = ReadMesh(reader, relationshipBuffers);
                loadState.AddMeshId(row.Id);
                model.MeshList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Mesh ReadMesh(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Mesh();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Mesh'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Mesh");
                return row;
            }

            reader.ReadStartElement("Mesh");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "RootPath":
                        row.RootPath = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Mesh'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeMeshShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <MeshList>\n");
            foreach (var row in model.MeshList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Mesh' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Mesh' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Mesh Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'Mesh' row '{row.Id}' is missing required property 'Name'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.RootPath))
                {
                    AppendElement(builder, "RootPath", row.RootPath!, "      ");
                }
                builder.Append("    </Mesh>\n");
            }
            builder.Append("  </MeshList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadOperationList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationList");
                return;
            }

            reader.ReadStartElement("OperationList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Operation", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'OperationList'.");
                }
                var row = ReadOperation(reader, relationshipBuffers);
                loadState.AddOperationId(row.Id);
                model.OperationList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Operation ReadOperation(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Operation();
            var relationships = new OperationRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Operation'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Operation");
                (relationshipBuffers.OperationRelationships ??= new List<OperationRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("Operation");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Operation'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.OperationRelationships ??= new List<OperationRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeOperationShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <OperationList>\n");
            foreach (var row in model.OperationList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Operation' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Operation' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Operation Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'Operation.MeshId' on row 'Operation:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'Operation.MeshId' on row 'Operation:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'Operation' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </Operation>\n");
            }
            builder.Append("  </OperationList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadOperationStepList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationStepList");
                return;
            }

            reader.ReadStartElement("OperationStepList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "OperationStep", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'OperationStepList'.");
                }
                var row = ReadOperationStep(reader, relationshipBuffers);
                loadState.AddOperationStepId(row.Id);
                model.OperationStepList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static OperationStep ReadOperationStep(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new OperationStep();
            var relationships = new OperationStepRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "OperationId":
                            relationships.OperationId = reader.Value;
                            break;
                        case "PreviousStepId":
                            relationships.PreviousStepId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'OperationStep'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationStep");
                (relationshipBuffers.OperationStepRelationships ??= new List<OperationStepRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("OperationStep");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Arguments":
                        row.Arguments = reader.ReadElementContentAsString();
                        break;
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Executable":
                        row.Executable = reader.ReadElementContentAsString();
                        break;
                    case "ExpectedExitCode":
                        row.ExpectedExitCode = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "WorkingDirectory":
                        row.WorkingDirectory = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'OperationStep'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.OperationStepRelationships ??= new List<OperationStepRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeOperationStepShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <OperationStepList>\n");
            foreach (var row in model.OperationStepList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'OperationStep' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'OperationStep' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <OperationStep Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var operationId = RequireIdentity(row.Operation?.Id, $"Relationship 'OperationStep.OperationId' on row 'OperationStep:{row.Id}' is empty.");
                if (!saveIndexes.OperationListById.TryGetValue(operationId, out var operationCanonical) || !ReferenceEquals(operationCanonical, row.Operation))
                {
                    throw new InvalidOperationException($"Relationship 'OperationStep.OperationId' on row 'OperationStep:{row.Id}' references an object that is not the canonical row for Id '{operationId}'.");
                }
                builder.Append(' ');
                builder.Append("OperationId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, operationId);
                builder.Append('"');
                if (row.PreviousStep != null)
                {
                    var previousStepId = RequireIdentity(row.PreviousStep?.Id, $"Relationship 'OperationStep.PreviousStepId' on row 'OperationStep:{row.Id}' is empty.");
                    if (!saveIndexes.OperationStepListById.TryGetValue(previousStepId, out var previousStepCanonical) || !ReferenceEquals(previousStepCanonical, row.PreviousStep))
                    {
                        throw new InvalidOperationException($"Relationship 'OperationStep.PreviousStepId' on row 'OperationStep:{row.Id}' references an object that is not the canonical row for Id '{previousStepId}'.");
                    }
                    builder.Append(' ');
                    builder.Append("PreviousStepId");
                    builder.Append("=\"");
                    AppendXmlAttribute(builder, previousStepId);
                    builder.Append('"');
                }
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Arguments))
                {
                    AppendElement(builder, "Arguments", row.Arguments!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Executable", RequireText(row.Executable, $"Entity 'OperationStep' row '{row.Id}' is missing required property 'Executable'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.ExpectedExitCode))
                {
                    AppendElement(builder, "ExpectedExitCode", row.ExpectedExitCode!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'OperationStep' row '{row.Id}' is missing required property 'Name'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.WorkingDirectory))
                {
                    AppendElement(builder, "WorkingDirectory", row.WorkingDirectory!, "      ");
                }
                builder.Append("    </OperationStep>\n");
            }
            builder.Append("  </OperationStepList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadSqlWorkspaceList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SqlWorkspaceList");
                return;
            }

            reader.ReadStartElement("SqlWorkspaceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "SqlWorkspace", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'SqlWorkspaceList'.");
                }
                var row = ReadSqlWorkspace(reader, relationshipBuffers);
                loadState.AddSqlWorkspaceId(row.Id);
                model.SqlWorkspaceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static SqlWorkspace ReadSqlWorkspace(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new SqlWorkspace();
            var relationships = new SqlWorkspaceRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "WorkspaceId":
                            relationships.WorkspaceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'SqlWorkspace'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("SqlWorkspace");
                (relationshipBuffers.SqlWorkspaceRelationships ??= new List<SqlWorkspaceRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("SqlWorkspace");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "ConnectionEnvironmentVariable":
                        row.ConnectionEnvironmentVariable = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'SqlWorkspace'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.SqlWorkspaceRelationships ??= new List<SqlWorkspaceRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeSqlWorkspaceShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <SqlWorkspaceList>\n");
            foreach (var row in model.SqlWorkspaceList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'SqlWorkspace' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'SqlWorkspace' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <SqlWorkspace Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var workspaceId = RequireIdentity(row.Workspace?.Id, $"Relationship 'SqlWorkspace.WorkspaceId' on row 'SqlWorkspace:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceListById.TryGetValue(workspaceId, out var workspaceCanonical) || !ReferenceEquals(workspaceCanonical, row.Workspace))
                {
                    throw new InvalidOperationException($"Relationship 'SqlWorkspace.WorkspaceId' on row 'SqlWorkspace:{row.Id}' references an object that is not the canonical row for Id '{workspaceId}'.");
                }
                builder.Append(' ');
                builder.Append("WorkspaceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, workspaceId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "ConnectionEnvironmentVariable", RequireText(row.ConnectionEnvironmentVariable, $"Entity 'SqlWorkspace' row '{row.Id}' is missing required property 'ConnectionEnvironmentVariable'."), "      ");
                builder.Append("    </SqlWorkspace>\n");
            }
            builder.Append("  </SqlWorkspaceList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadWorkspaceList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceList");
                return;
            }

            reader.ReadStartElement("WorkspaceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Workspace", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'WorkspaceList'.");
                }
                var row = ReadWorkspace(reader, relationshipBuffers);
                loadState.AddWorkspaceId(row.Id);
                model.WorkspaceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Workspace ReadWorkspace(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Workspace();
            var relationships = new WorkspaceRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Workspace'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Workspace");
                (relationshipBuffers.WorkspaceRelationships ??= new List<WorkspaceRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("Workspace");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "ModelName":
                        row.ModelName = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Workspace'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.WorkspaceRelationships ??= new List<WorkspaceRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeWorkspaceShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <WorkspaceList>\n");
            foreach (var row in model.WorkspaceList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Workspace' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Workspace' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Workspace Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'Workspace.MeshId' on row 'Workspace:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'Workspace.MeshId' on row 'Workspace:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.ModelName))
                {
                    AppendElement(builder, "ModelName", row.ModelName!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'Workspace' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </Workspace>\n");
            }
            builder.Append("  </WorkspaceList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadXmlWorkspaceList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("XmlWorkspaceList");
                return;
            }

            reader.ReadStartElement("XmlWorkspaceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "XmlWorkspace", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'XmlWorkspaceList'.");
                }
                var row = ReadXmlWorkspace(reader, relationshipBuffers);
                loadState.AddXmlWorkspaceId(row.Id);
                model.XmlWorkspaceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static XmlWorkspace ReadXmlWorkspace(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new XmlWorkspace();
            var relationships = new XmlWorkspaceRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "WorkspaceId":
                            relationships.WorkspaceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'XmlWorkspace'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("XmlWorkspace");
                (relationshipBuffers.XmlWorkspaceRelationships ??= new List<XmlWorkspaceRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("XmlWorkspace");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Path":
                        row.Path = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'XmlWorkspace'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.XmlWorkspaceRelationships ??= new List<XmlWorkspaceRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeXmlWorkspaceShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <XmlWorkspaceList>\n");
            foreach (var row in model.XmlWorkspaceList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'XmlWorkspace' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'XmlWorkspace' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <XmlWorkspace Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var workspaceId = RequireIdentity(row.Workspace?.Id, $"Relationship 'XmlWorkspace.WorkspaceId' on row 'XmlWorkspace:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceListById.TryGetValue(workspaceId, out var workspaceCanonical) || !ReferenceEquals(workspaceCanonical, row.Workspace))
                {
                    throw new InvalidOperationException($"Relationship 'XmlWorkspace.WorkspaceId' on row 'XmlWorkspace:{row.Id}' references an object that is not the canonical row for Id '{workspaceId}'.");
                }
                builder.Append(' ');
                builder.Append("WorkspaceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, workspaceId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Path", RequireText(row.Path, $"Entity 'XmlWorkspace' row '{row.Id}' is missing required property 'Path'."), "      ");
                builder.Append("    </XmlWorkspace>\n");
            }
            builder.Append("  </XmlWorkspaceList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private sealed class CSharpWorkspaceRelationships
        {
            public CSharpWorkspace Row { get; set; } = null!;
            public string WorkspaceId { get; set; } = string.Empty;
        }

        private sealed class OperationRelationships
        {
            public Operation Row { get; set; } = null!;
            public string MeshId { get; set; } = string.Empty;
        }

        private sealed class OperationStepRelationships
        {
            public OperationStep Row { get; set; } = null!;
            public string OperationId { get; set; } = string.Empty;
            public string PreviousStepId { get; set; } = string.Empty;
        }

        private sealed class SqlWorkspaceRelationships
        {
            public SqlWorkspace Row { get; set; } = null!;
            public string WorkspaceId { get; set; } = string.Empty;
        }

        private sealed class WorkspaceRelationships
        {
            public Workspace Row { get; set; } = null!;
            public string MeshId { get; set; } = string.Empty;
        }

        private sealed class XmlWorkspaceRelationships
        {
            public XmlWorkspace Row { get; set; } = null!;
            public string WorkspaceId { get; set; } = string.Empty;
        }

        private sealed class RelationshipBuffers
        {
            public List<CSharpWorkspaceRelationships>? CSharpWorkspaceRelationships { get; set; }
            public List<OperationRelationships>? OperationRelationships { get; set; }
            public List<OperationStepRelationships>? OperationStepRelationships { get; set; }
            public List<SqlWorkspaceRelationships>? SqlWorkspaceRelationships { get; set; }
            public List<WorkspaceRelationships>? WorkspaceRelationships { get; set; }
            public List<XmlWorkspaceRelationships>? XmlWorkspaceRelationships { get; set; }
        }

        private static void ResolveRelationshipGroup1(LoadIndexes loadIndexes, RelationshipBuffers relationshipBuffers)
        {
            foreach (var relationship in relationshipBuffers.CSharpWorkspaceRelationships ?? Enumerable.Empty<CSharpWorkspaceRelationships>())
            {
                relationship.Row.Workspace = RequireTarget(
                    loadIndexes.WorkspaceListById,
                    relationship.WorkspaceId,
                    "CSharpWorkspace",
                    relationship.Row.Id,
                    "WorkspaceId");
            }

            foreach (var relationship in relationshipBuffers.OperationRelationships ?? Enumerable.Empty<OperationRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "Operation",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.OperationStepRelationships ?? Enumerable.Empty<OperationStepRelationships>())
            {
                relationship.Row.Operation = RequireTarget(
                    loadIndexes.OperationListById,
                    relationship.OperationId,
                    "OperationStep",
                    relationship.Row.Id,
                    "OperationId");
            }

            foreach (var relationship in relationshipBuffers.OperationStepRelationships ?? Enumerable.Empty<OperationStepRelationships>())
            {
                relationship.Row.PreviousStep = string.IsNullOrWhiteSpace(relationship.PreviousStepId)
                    ? null
                    : RequireTarget(
                        loadIndexes.OperationStepListById,
                        relationship.PreviousStepId,
                        "OperationStep",
                        relationship.Row.Id,
                        "PreviousStepId");
            }

            foreach (var relationship in relationshipBuffers.SqlWorkspaceRelationships ?? Enumerable.Empty<SqlWorkspaceRelationships>())
            {
                relationship.Row.Workspace = RequireTarget(
                    loadIndexes.WorkspaceListById,
                    relationship.WorkspaceId,
                    "SqlWorkspace",
                    relationship.Row.Id,
                    "WorkspaceId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceRelationships ?? Enumerable.Empty<WorkspaceRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "Workspace",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.XmlWorkspaceRelationships ?? Enumerable.Empty<XmlWorkspaceRelationships>())
            {
                relationship.Row.Workspace = RequireTarget(
                    loadIndexes.WorkspaceListById,
                    relationship.WorkspaceId,
                    "XmlWorkspace",
                    relationship.Row.Id,
                    "WorkspaceId");
            }

        }

        private static readonly string[] ShardFileNames =
        {
            "CSharpWorkspace.xml",
            "Mesh.xml",
            "Operation.xml",
            "OperationStep.xml",
            "SqlWorkspace.xml",
            "Workspace.xml",
            "XmlWorkspace.xml",
        };

        private static HashSet<string> BuildExpectedShardPaths(string instanceDirectoryPath)
        {
            var expectedShardPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var shardFileName in ShardFileNames)
            {
                expectedShardPaths.Add(Path.GetFullPath(Path.Combine(instanceDirectoryPath, shardFileName)));
            }

            return expectedShardPaths;
        }

        private sealed class LoadState
        {
            private HashSet<string>? cSharpWorkspaceIds;

            public void AddCSharpWorkspaceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'CSharpWorkspace' contains a row with empty Id.");
                cSharpWorkspaceIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!cSharpWorkspaceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'CSharpWorkspace' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? meshIds;

            public void AddMeshId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Mesh' contains a row with empty Id.");
                meshIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!meshIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Mesh' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? operationIds;

            public void AddOperationId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Operation' contains a row with empty Id.");
                operationIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!operationIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Operation' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? operationStepIds;

            public void AddOperationStepId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'OperationStep' contains a row with empty Id.");
                operationStepIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!operationStepIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'OperationStep' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? sqlWorkspaceIds;

            public void AddSqlWorkspaceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'SqlWorkspace' contains a row with empty Id.");
                sqlWorkspaceIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!sqlWorkspaceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'SqlWorkspace' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? workspaceIds;

            public void AddWorkspaceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Workspace' contains a row with empty Id.");
                workspaceIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!workspaceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Workspace' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? xmlWorkspaceIds;

            public void AddXmlWorkspaceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'XmlWorkspace' contains a row with empty Id.");
                xmlWorkspaceIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!xmlWorkspaceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'XmlWorkspace' contains duplicate Id '{normalizedId}'.");
                }
            }

        }

        private sealed class LoadIndexes
        {
            private readonly MetaMeshModel model;

            public LoadIndexes(MetaMeshModel model)
            {
                this.model = model;
            }

            private Dictionary<string, CSharpWorkspace>? cSharpWorkspaceListById;

            public Dictionary<string, CSharpWorkspace> CSharpWorkspaceListById => cSharpWorkspaceListById ??= BuildById(model.CSharpWorkspaceList, row => row.Id, "CSharpWorkspace");

            private Dictionary<string, Mesh>? meshListById;

            public Dictionary<string, Mesh> MeshListById => meshListById ??= BuildById(model.MeshList, row => row.Id, "Mesh");

            private Dictionary<string, Operation>? operationListById;

            public Dictionary<string, Operation> OperationListById => operationListById ??= BuildById(model.OperationList, row => row.Id, "Operation");

            private Dictionary<string, OperationStep>? operationStepListById;

            public Dictionary<string, OperationStep> OperationStepListById => operationStepListById ??= BuildById(model.OperationStepList, row => row.Id, "OperationStep");

            private Dictionary<string, SqlWorkspace>? sqlWorkspaceListById;

            public Dictionary<string, SqlWorkspace> SqlWorkspaceListById => sqlWorkspaceListById ??= BuildById(model.SqlWorkspaceList, row => row.Id, "SqlWorkspace");

            private Dictionary<string, Workspace>? workspaceListById;

            public Dictionary<string, Workspace> WorkspaceListById => workspaceListById ??= BuildById(model.WorkspaceList, row => row.Id, "Workspace");

            private Dictionary<string, XmlWorkspace>? xmlWorkspaceListById;

            public Dictionary<string, XmlWorkspace> XmlWorkspaceListById => xmlWorkspaceListById ??= BuildById(model.XmlWorkspaceList, row => row.Id, "XmlWorkspace");

        }

        private sealed class SaveIndexes
        {
            private readonly MetaMeshModel model;

            public SaveIndexes(MetaMeshModel model)
            {
                this.model = model;
            }

            private Dictionary<string, CSharpWorkspace>? cSharpWorkspaceListById;

            public Dictionary<string, CSharpWorkspace> CSharpWorkspaceListById => cSharpWorkspaceListById ??= BuildById(model.CSharpWorkspaceList, row => row.Id, "CSharpWorkspace");

            private Dictionary<string, Mesh>? meshListById;

            public Dictionary<string, Mesh> MeshListById => meshListById ??= BuildById(model.MeshList, row => row.Id, "Mesh");

            private Dictionary<string, Operation>? operationListById;

            public Dictionary<string, Operation> OperationListById => operationListById ??= BuildById(model.OperationList, row => row.Id, "Operation");

            private Dictionary<string, OperationStep>? operationStepListById;

            public Dictionary<string, OperationStep> OperationStepListById => operationStepListById ??= BuildById(model.OperationStepList, row => row.Id, "OperationStep");

            private Dictionary<string, SqlWorkspace>? sqlWorkspaceListById;

            public Dictionary<string, SqlWorkspace> SqlWorkspaceListById => sqlWorkspaceListById ??= BuildById(model.SqlWorkspaceList, row => row.Id, "SqlWorkspace");

            private Dictionary<string, Workspace>? workspaceListById;

            public Dictionary<string, Workspace> WorkspaceListById => workspaceListById ??= BuildById(model.WorkspaceList, row => row.Id, "Workspace");

            private Dictionary<string, XmlWorkspace>? xmlWorkspaceListById;

            public Dictionary<string, XmlWorkspace> XmlWorkspaceListById => xmlWorkspaceListById ??= BuildById(model.XmlWorkspaceList, row => row.Id, "XmlWorkspace");

        }

        private static readonly Lazy<bool> RuntimeExtendedShape = new(DetectRuntimeExtendedShape);

        private static bool HasRuntimeExtendedShape()
        {
            return RuntimeExtendedShape.Value;
        }

        private static bool DetectRuntimeExtendedShape()
        {
            if (HasRuntimeExtendedEntityShapeGroup1())
            {
                return true;
            }

            return HasUnexpectedModelLists();
        }

        private static bool HasRuntimeExtendedEntityShapeGroup1()
        {
            if (HasUnexpectedProperties(typeof(CSharpWorkspace),
                "Id",
                "Path",
                "Workspace"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Mesh),
                "Id",
                "Description",
                "Name",
                "RootPath"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Operation),
                "Id",
                "Description",
                "Name",
                "Mesh"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(OperationStep),
                "Id",
                "Arguments",
                "Description",
                "Executable",
                "ExpectedExitCode",
                "Name",
                "WorkingDirectory",
                "Operation",
                "PreviousStep"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(SqlWorkspace),
                "Id",
                "ConnectionEnvironmentVariable",
                "Workspace"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(Workspace),
                "Id",
                "Description",
                "ModelName",
                "Name",
                "Mesh"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(XmlWorkspace),
                "Id",
                "Path",
                "Workspace"))
            {
                return true;
            }

            return false;
        }

        private static bool HasUnexpectedModelLists()
        {
            var knownLists = new HashSet<string>(StringComparer.Ordinal)
            {
                "CSharpWorkspaceList",
                "MeshList",
                "OperationList",
                "OperationStepList",
                "SqlWorkspaceList",
                "WorkspaceList",
                "XmlWorkspaceList",
            };
            return typeof(MetaMeshModel).GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Any(property =>
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(List<>) &&
                    !knownLists.Contains(property.Name));
        }

        private static bool HasUnexpectedProperties(Type type, params string[] knownProperties)
        {
            return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanRead && property.CanWrite && property.GetIndexParameters().Length == 0)
                .Any(property => !knownProperties.Contains(property.Name, StringComparer.Ordinal));
        }

        private static Dictionary<string, T> BuildById<T>(IEnumerable<T> rows, Func<T, string> getId, string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }
            return rowsById;
        }

        private static T RequireTarget<T>(Dictionary<string, T> rowsById, string targetId, string sourceEntityName, string sourceId, string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidDataException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }
            return target;
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var identity = value ?? string.Empty;
            if (string.IsNullOrWhiteSpace(identity))
            {
                throw new InvalidOperationException(errorMessage);
            }
            if (!string.Equals(identity, identity.Trim(), StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"{errorMessage} Identity cannot contain leading or trailing whitespace.");
            }
            if (identity.Length > 450)
            {
                throw new InvalidOperationException($"{errorMessage} Identity cannot exceed 450 characters.");
            }
            return identity;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return value;
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string indent)
        {
            builder.Append(indent);
            builder.Append('<');
            builder.Append(name);
            builder.Append('>');
            AppendXmlText(builder, value);
            builder.Append("</");
            builder.Append(name);
            builder.Append(">\n");
        }

        private static void AppendXmlAttribute(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    case '"': builder.Append("&quot;"); break;
                    case '\'': builder.Append("&apos;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static void AppendXmlText(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static bool IsNamespaceDeclaration(XmlReader reader)
        {
            return string.Equals(reader.Prefix, "xmlns", StringComparison.Ordinal) ||
                   string.Equals(reader.LocalName, "xmlns", StringComparison.Ordinal);
        }

        private static void DeleteIfExists(string path)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

    }

}
