// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Meta.Core.Serialization;

namespace MetaMesh
{
    public sealed partial class MetaMeshModel : IMetaWorkspaceModel<MetaMeshModel>
    {
        public static MetaMeshModel CreateEmpty() => new();

        public List<Mesh> MeshList { get; set; } = new();

        public List<MeshSuggestion> MeshSuggestionList { get; set; } = new();

        public List<ModelProvider> ModelProviderList { get; set; } = new();

        public List<OperationCapability> OperationCapabilityList { get; set; } = new();

        public List<OperationEffect> OperationEffectList { get; set; } = new();

        public List<ProviderBinding> ProviderBindingList { get; set; } = new();

        public List<WorkspaceInstance> WorkspaceInstanceList { get; set; } = new();

        public List<WorkspaceLink> WorkspaceLinkList { get; set; } = new();

        public List<WorkspaceMount> WorkspaceMountList { get; set; } = new();

        public static MetaMeshModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaMeshModelXmlSerializer.Load(workspacePath, searchUpward);
        }

        public static Task<MetaMeshModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaMeshModelXmlSerializer.Save(this, workspacePath);
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }

    internal static class MetaMeshModelXmlSerializer
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        internal static MetaMeshModel Load(string workspacePath, bool searchUpward)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (searchUpward)
            {
                throw new NotSupportedException("Typed workspace loading does not search parent directories. Pass an explicit workspace path.");
            }

            if (HasRuntimeExtendedShape())
            {
                return TypedWorkspaceXmlSerializer.Load<MetaMeshModel>(workspacePath, searchUpward);
            }

            var workspaceRootPath = TypedWorkspaceXmlSerializer.RequireWorkspace<MetaMeshModel>(workspacePath);

            var model = new MetaMeshModel();
            var loadState = new LoadState();
            var relationshipBuffers = new RelationshipBuffers();
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            if (!Directory.Exists(instanceDirectoryPath))
            {
                return model;
            }

            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                LoadShard(model, shardPath, loadState, relationshipBuffers);
            }

            var loadIndexes = new LoadIndexes(model);
            ResolveRelationshipGroup1(loadIndexes, relationshipBuffers);
            return model;
        }

        internal static void Save(MetaMeshModel model, string workspacePath)
        {
            ArgumentNullException.ThrowIfNull(model);
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (HasRuntimeExtendedShape())
            {
                TypedWorkspaceXmlSerializer.Save(model, workspacePath);
                return;
            }

            TypedWorkspaceXmlSerializer.SaveModel(model, workspacePath);

            var saveIndexes = new SaveIndexes(model);

            var workspaceRootPath = Path.GetFullPath(workspacePath);
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            Directory.CreateDirectory(instanceDirectoryPath);
            var expectedShardPaths = BuildExpectedShardPaths(instanceDirectoryPath);
            SaveShardGroup1(model, instanceDirectoryPath, saveIndexes);
            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                if (!expectedShardPaths.Contains(Path.GetFullPath(shardPath)))
                {
                    File.Delete(shardPath);
                }
            }
        }

        private static void SaveShardGroup1(MetaMeshModel model, string instanceDirectoryPath, SaveIndexes saveIndexes)
        {
            model.MeshList ??= new List<Mesh>();
            var meshShardPath = Path.Combine(instanceDirectoryPath, "Mesh.xml");
            if (model.MeshList.Count == 0)
            {
                DeleteIfExists(meshShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(meshShardPath, SerializeMeshShard(model, saveIndexes));
            }

            model.MeshSuggestionList ??= new List<MeshSuggestion>();
            var meshSuggestionShardPath = Path.Combine(instanceDirectoryPath, "MeshSuggestion.xml");
            if (model.MeshSuggestionList.Count == 0)
            {
                DeleteIfExists(meshSuggestionShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(meshSuggestionShardPath, SerializeMeshSuggestionShard(model, saveIndexes));
            }

            model.ModelProviderList ??= new List<ModelProvider>();
            var modelProviderShardPath = Path.Combine(instanceDirectoryPath, "ModelProvider.xml");
            if (model.ModelProviderList.Count == 0)
            {
                DeleteIfExists(modelProviderShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(modelProviderShardPath, SerializeModelProviderShard(model, saveIndexes));
            }

            model.OperationCapabilityList ??= new List<OperationCapability>();
            var operationCapabilityShardPath = Path.Combine(instanceDirectoryPath, "OperationCapability.xml");
            if (model.OperationCapabilityList.Count == 0)
            {
                DeleteIfExists(operationCapabilityShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(operationCapabilityShardPath, SerializeOperationCapabilityShard(model, saveIndexes));
            }

            model.OperationEffectList ??= new List<OperationEffect>();
            var operationEffectShardPath = Path.Combine(instanceDirectoryPath, "OperationEffect.xml");
            if (model.OperationEffectList.Count == 0)
            {
                DeleteIfExists(operationEffectShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(operationEffectShardPath, SerializeOperationEffectShard(model, saveIndexes));
            }

            model.ProviderBindingList ??= new List<ProviderBinding>();
            var providerBindingShardPath = Path.Combine(instanceDirectoryPath, "ProviderBinding.xml");
            if (model.ProviderBindingList.Count == 0)
            {
                DeleteIfExists(providerBindingShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(providerBindingShardPath, SerializeProviderBindingShard(model, saveIndexes));
            }

            model.WorkspaceInstanceList ??= new List<WorkspaceInstance>();
            var workspaceInstanceShardPath = Path.Combine(instanceDirectoryPath, "WorkspaceInstance.xml");
            if (model.WorkspaceInstanceList.Count == 0)
            {
                DeleteIfExists(workspaceInstanceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(workspaceInstanceShardPath, SerializeWorkspaceInstanceShard(model, saveIndexes));
            }

            model.WorkspaceLinkList ??= new List<WorkspaceLink>();
            var workspaceLinkShardPath = Path.Combine(instanceDirectoryPath, "WorkspaceLink.xml");
            if (model.WorkspaceLinkList.Count == 0)
            {
                DeleteIfExists(workspaceLinkShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(workspaceLinkShardPath, SerializeWorkspaceLinkShard(model, saveIndexes));
            }

            model.WorkspaceMountList ??= new List<WorkspaceMount>();
            var workspaceMountShardPath = Path.Combine(instanceDirectoryPath, "WorkspaceMount.xml");
            if (model.WorkspaceMountList.Count == 0)
            {
                DeleteIfExists(workspaceMountShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(workspaceMountShardPath, SerializeWorkspaceMountShard(model, saveIndexes));
            }

        }

        private static void LoadShard(MetaMeshModel model, string shardPath, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            using var reader = XmlReader.Create(shardPath, new XmlReaderSettings
            {
                IgnoreComments = true,
                IgnoreWhitespace = true,
            });
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element || !string.Equals(reader.LocalName, "MetaMesh", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"Instance XML '{shardPath}' root must be <MetaMesh>.");
            }
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return;
            }
            reader.ReadStartElement("MetaMesh");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "MeshList":
                        LoadMeshList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "MeshSuggestionList":
                        LoadMeshSuggestionList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "ModelProviderList":
                        LoadModelProviderList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "OperationCapabilityList":
                        LoadOperationCapabilityList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "OperationEffectList":
                        LoadOperationEffectList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "ProviderBindingList":
                        LoadProviderBindingList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "WorkspaceInstanceList":
                        LoadWorkspaceInstanceList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "WorkspaceLinkList":
                        LoadWorkspaceLinkList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "WorkspaceMountList":
                        LoadWorkspaceMountList(model, reader, loadState, relationshipBuffers);
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in '{shardPath}'.");
                }
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static void LoadMeshList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("MeshList");
                return;
            }

            reader.ReadStartElement("MeshList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Mesh", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'MeshList'.");
                }
                var row = ReadMesh(reader, relationshipBuffers);
                loadState.AddMeshId(row.Id);
                model.MeshList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Mesh ReadMesh(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Mesh();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Mesh'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Mesh");
                return row;
            }

            reader.ReadStartElement("Mesh");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "RootPath":
                        row.RootPath = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Mesh'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeMeshShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <MeshList>\n");
            foreach (var row in model.MeshList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Mesh' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Mesh' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Mesh Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'Mesh' row '{row.Id}' is missing required property 'Name'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.RootPath))
                {
                    AppendElement(builder, "RootPath", row.RootPath!, "      ");
                }
                builder.Append("    </Mesh>\n");
            }
            builder.Append("  </MeshList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadMeshSuggestionList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("MeshSuggestionList");
                return;
            }

            reader.ReadStartElement("MeshSuggestionList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "MeshSuggestion", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'MeshSuggestionList'.");
                }
                var row = ReadMeshSuggestion(reader, relationshipBuffers);
                loadState.AddMeshSuggestionId(row.Id);
                model.MeshSuggestionList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static MeshSuggestion ReadMeshSuggestion(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new MeshSuggestion();
            var relationships = new MeshSuggestionRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        case "WorkspaceInstanceId":
                            relationships.WorkspaceInstanceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'MeshSuggestion'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("MeshSuggestion");
                (relationshipBuffers.MeshSuggestionRelationships ??= new List<MeshSuggestionRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("MeshSuggestion");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Message":
                        row.Message = reader.ReadElementContentAsString();
                        break;
                    case "Severity":
                        row.Severity = reader.ReadElementContentAsString();
                        break;
                    case "SuggestedHandle":
                        row.SuggestedHandle = reader.ReadElementContentAsString();
                        break;
                    case "SuggestedLifecycle":
                        row.SuggestedLifecycle = reader.ReadElementContentAsString();
                        break;
                    case "SuggestedPath":
                        row.SuggestedPath = reader.ReadElementContentAsString();
                        break;
                    case "SuggestedWorkspaceKind":
                        row.SuggestedWorkspaceKind = reader.ReadElementContentAsString();
                        break;
                    case "SuggestionKind":
                        row.SuggestionKind = reader.ReadElementContentAsString();
                        break;
                    case "WorkspaceHandle":
                        row.WorkspaceHandle = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'MeshSuggestion'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.MeshSuggestionRelationships ??= new List<MeshSuggestionRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeMeshSuggestionShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <MeshSuggestionList>\n");
            foreach (var row in model.MeshSuggestionList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'MeshSuggestion' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'MeshSuggestion' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <MeshSuggestion Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'MeshSuggestion.MeshId' on row 'MeshSuggestion:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'MeshSuggestion.MeshId' on row 'MeshSuggestion:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                if (row.WorkspaceInstance != null)
                {
                    var workspaceInstanceId = RequireIdentity(row.WorkspaceInstance?.Id, $"Relationship 'MeshSuggestion.WorkspaceInstanceId' on row 'MeshSuggestion:{row.Id}' is empty.");
                    if (!saveIndexes.WorkspaceInstanceListById.TryGetValue(workspaceInstanceId, out var workspaceInstanceCanonical) || !ReferenceEquals(workspaceInstanceCanonical, row.WorkspaceInstance))
                    {
                        throw new InvalidOperationException($"Relationship 'MeshSuggestion.WorkspaceInstanceId' on row 'MeshSuggestion:{row.Id}' references an object that is not the canonical row for Id '{workspaceInstanceId}'.");
                    }
                    builder.Append(' ');
                    builder.Append("WorkspaceInstanceId");
                    builder.Append("=\"");
                    AppendXmlAttribute(builder, workspaceInstanceId);
                    builder.Append('"');
                }
                builder.Append(">\n");
                AppendElement(builder, "Message", RequireText(row.Message, $"Entity 'MeshSuggestion' row '{row.Id}' is missing required property 'Message'."), "      ");
                AppendElement(builder, "Severity", RequireText(row.Severity, $"Entity 'MeshSuggestion' row '{row.Id}' is missing required property 'Severity'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.SuggestedHandle))
                {
                    AppendElement(builder, "SuggestedHandle", row.SuggestedHandle!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.SuggestedLifecycle))
                {
                    AppendElement(builder, "SuggestedLifecycle", row.SuggestedLifecycle!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.SuggestedPath))
                {
                    AppendElement(builder, "SuggestedPath", row.SuggestedPath!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.SuggestedWorkspaceKind))
                {
                    AppendElement(builder, "SuggestedWorkspaceKind", row.SuggestedWorkspaceKind!, "      ");
                }
                AppendElement(builder, "SuggestionKind", RequireText(row.SuggestionKind, $"Entity 'MeshSuggestion' row '{row.Id}' is missing required property 'SuggestionKind'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.WorkspaceHandle))
                {
                    AppendElement(builder, "WorkspaceHandle", row.WorkspaceHandle!, "      ");
                }
                builder.Append("    </MeshSuggestion>\n");
            }
            builder.Append("  </MeshSuggestionList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadModelProviderList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ModelProviderList");
                return;
            }

            reader.ReadStartElement("ModelProviderList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "ModelProvider", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'ModelProviderList'.");
                }
                var row = ReadModelProvider(reader, relationshipBuffers);
                loadState.AddModelProviderId(row.Id);
                model.ModelProviderList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static ModelProvider ReadModelProvider(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new ModelProvider();
            var relationships = new ModelProviderRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'ModelProvider'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ModelProvider");
                (relationshipBuffers.ModelProviderRelationships ??= new List<ModelProviderRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("ModelProvider");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "ExecutableName":
                        row.ExecutableName = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "ProviderKind":
                        row.ProviderKind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'ModelProvider'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.ModelProviderRelationships ??= new List<ModelProviderRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeModelProviderShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <ModelProviderList>\n");
            foreach (var row in model.ModelProviderList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'ModelProvider' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'ModelProvider' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <ModelProvider Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'ModelProvider.MeshId' on row 'ModelProvider:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'ModelProvider.MeshId' on row 'ModelProvider:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.ExecutableName))
                {
                    AppendElement(builder, "ExecutableName", row.ExecutableName!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'ModelProvider' row '{row.Id}' is missing required property 'Name'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.ProviderKind))
                {
                    AppendElement(builder, "ProviderKind", row.ProviderKind!, "      ");
                }
                builder.Append("    </ModelProvider>\n");
            }
            builder.Append("  </ModelProviderList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadOperationCapabilityList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationCapabilityList");
                return;
            }

            reader.ReadStartElement("OperationCapabilityList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "OperationCapability", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'OperationCapabilityList'.");
                }
                var row = ReadOperationCapability(reader, relationshipBuffers);
                loadState.AddOperationCapabilityId(row.Id);
                model.OperationCapabilityList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static OperationCapability ReadOperationCapability(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new OperationCapability();
            var relationships = new OperationCapabilityRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "ModelProviderId":
                            relationships.ModelProviderId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'OperationCapability'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationCapability");
                (relationshipBuffers.OperationCapabilityRelationships ??= new List<OperationCapabilityRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("OperationCapability");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "CanHandleHostRequest":
                        row.CanHandleHostRequest = reader.ReadElementContentAsString();
                        break;
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'OperationCapability'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.OperationCapabilityRelationships ??= new List<OperationCapabilityRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeOperationCapabilityShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <OperationCapabilityList>\n");
            foreach (var row in model.OperationCapabilityList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'OperationCapability' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'OperationCapability' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <OperationCapability Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var modelProviderId = RequireIdentity(row.ModelProvider?.Id, $"Relationship 'OperationCapability.ModelProviderId' on row 'OperationCapability:{row.Id}' is empty.");
                if (!saveIndexes.ModelProviderListById.TryGetValue(modelProviderId, out var modelProviderCanonical) || !ReferenceEquals(modelProviderCanonical, row.ModelProvider))
                {
                    throw new InvalidOperationException($"Relationship 'OperationCapability.ModelProviderId' on row 'OperationCapability:{row.Id}' references an object that is not the canonical row for Id '{modelProviderId}'.");
                }
                builder.Append(' ');
                builder.Append("ModelProviderId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, modelProviderId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.CanHandleHostRequest))
                {
                    AppendElement(builder, "CanHandleHostRequest", row.CanHandleHostRequest!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'OperationCapability' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </OperationCapability>\n");
            }
            builder.Append("  </OperationCapabilityList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadOperationEffectList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationEffectList");
                return;
            }

            reader.ReadStartElement("OperationEffectList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "OperationEffect", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'OperationEffectList'.");
                }
                var row = ReadOperationEffect(reader, relationshipBuffers);
                loadState.AddOperationEffectId(row.Id);
                model.OperationEffectList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static OperationEffect ReadOperationEffect(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new OperationEffect();
            var relationships = new OperationEffectRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "OperationCapabilityId":
                            relationships.OperationCapabilityId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'OperationEffect'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("OperationEffect");
                (relationshipBuffers.OperationEffectRelationships ??= new List<OperationEffectRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("OperationEffect");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "EffectKind":
                        row.EffectKind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'OperationEffect'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.OperationEffectRelationships ??= new List<OperationEffectRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeOperationEffectShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <OperationEffectList>\n");
            foreach (var row in model.OperationEffectList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'OperationEffect' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'OperationEffect' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <OperationEffect Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var operationCapabilityId = RequireIdentity(row.OperationCapability?.Id, $"Relationship 'OperationEffect.OperationCapabilityId' on row 'OperationEffect:{row.Id}' is empty.");
                if (!saveIndexes.OperationCapabilityListById.TryGetValue(operationCapabilityId, out var operationCapabilityCanonical) || !ReferenceEquals(operationCapabilityCanonical, row.OperationCapability))
                {
                    throw new InvalidOperationException($"Relationship 'OperationEffect.OperationCapabilityId' on row 'OperationEffect:{row.Id}' references an object that is not the canonical row for Id '{operationCapabilityId}'.");
                }
                builder.Append(' ');
                builder.Append("OperationCapabilityId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, operationCapabilityId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "EffectKind", RequireText(row.EffectKind, $"Entity 'OperationEffect' row '{row.Id}' is missing required property 'EffectKind'."), "      ");
                builder.Append("    </OperationEffect>\n");
            }
            builder.Append("  </OperationEffectList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadProviderBindingList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ProviderBindingList");
                return;
            }

            reader.ReadStartElement("ProviderBindingList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "ProviderBinding", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'ProviderBindingList'.");
                }
                var row = ReadProviderBinding(reader, relationshipBuffers);
                loadState.AddProviderBindingId(row.Id);
                model.ProviderBindingList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static ProviderBinding ReadProviderBinding(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new ProviderBinding();
            var relationships = new ProviderBindingRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "ModelProviderId":
                            relationships.ModelProviderId = reader.Value;
                            break;
                        case "WorkspaceInstanceId":
                            relationships.WorkspaceInstanceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'ProviderBinding'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ProviderBinding");
                (relationshipBuffers.ProviderBindingRelationships ??= new List<ProviderBindingRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("ProviderBinding");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "SupportedModelName":
                        row.SupportedModelName = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'ProviderBinding'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.ProviderBindingRelationships ??= new List<ProviderBindingRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeProviderBindingShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <ProviderBindingList>\n");
            foreach (var row in model.ProviderBindingList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'ProviderBinding' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'ProviderBinding' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <ProviderBinding Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var modelProviderId = RequireIdentity(row.ModelProvider?.Id, $"Relationship 'ProviderBinding.ModelProviderId' on row 'ProviderBinding:{row.Id}' is empty.");
                if (!saveIndexes.ModelProviderListById.TryGetValue(modelProviderId, out var modelProviderCanonical) || !ReferenceEquals(modelProviderCanonical, row.ModelProvider))
                {
                    throw new InvalidOperationException($"Relationship 'ProviderBinding.ModelProviderId' on row 'ProviderBinding:{row.Id}' references an object that is not the canonical row for Id '{modelProviderId}'.");
                }
                builder.Append(' ');
                builder.Append("ModelProviderId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, modelProviderId);
                builder.Append('"');
                var workspaceInstanceId = RequireIdentity(row.WorkspaceInstance?.Id, $"Relationship 'ProviderBinding.WorkspaceInstanceId' on row 'ProviderBinding:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceInstanceListById.TryGetValue(workspaceInstanceId, out var workspaceInstanceCanonical) || !ReferenceEquals(workspaceInstanceCanonical, row.WorkspaceInstance))
                {
                    throw new InvalidOperationException($"Relationship 'ProviderBinding.WorkspaceInstanceId' on row 'ProviderBinding:{row.Id}' references an object that is not the canonical row for Id '{workspaceInstanceId}'.");
                }
                builder.Append(' ');
                builder.Append("WorkspaceInstanceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, workspaceInstanceId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.SupportedModelName))
                {
                    AppendElement(builder, "SupportedModelName", row.SupportedModelName!, "      ");
                }
                builder.Append("    </ProviderBinding>\n");
            }
            builder.Append("  </ProviderBindingList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadWorkspaceInstanceList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceInstanceList");
                return;
            }

            reader.ReadStartElement("WorkspaceInstanceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "WorkspaceInstance", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'WorkspaceInstanceList'.");
                }
                var row = ReadWorkspaceInstance(reader, relationshipBuffers);
                loadState.AddWorkspaceInstanceId(row.Id);
                model.WorkspaceInstanceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static WorkspaceInstance ReadWorkspaceInstance(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new WorkspaceInstance();
            var relationships = new WorkspaceInstanceRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'WorkspaceInstance'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceInstance");
                (relationshipBuffers.WorkspaceInstanceRelationships ??= new List<WorkspaceInstanceRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("WorkspaceInstance");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "DisplayName":
                        row.DisplayName = reader.ReadElementContentAsString();
                        break;
                    case "Handle":
                        row.Handle = reader.ReadElementContentAsString();
                        break;
                    case "Lifecycle":
                        row.Lifecycle = reader.ReadElementContentAsString();
                        break;
                    case "ModelName":
                        row.ModelName = reader.ReadElementContentAsString();
                        break;
                    case "Summary":
                        row.Summary = reader.ReadElementContentAsString();
                        break;
                    case "WorkspaceKind":
                        row.WorkspaceKind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'WorkspaceInstance'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.WorkspaceInstanceRelationships ??= new List<WorkspaceInstanceRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeWorkspaceInstanceShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <WorkspaceInstanceList>\n");
            foreach (var row in model.WorkspaceInstanceList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'WorkspaceInstance' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'WorkspaceInstance' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <WorkspaceInstance Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'WorkspaceInstance.MeshId' on row 'WorkspaceInstance:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'WorkspaceInstance.MeshId' on row 'WorkspaceInstance:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.DisplayName))
                {
                    AppendElement(builder, "DisplayName", row.DisplayName!, "      ");
                }
                AppendElement(builder, "Handle", RequireText(row.Handle, $"Entity 'WorkspaceInstance' row '{row.Id}' is missing required property 'Handle'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.Lifecycle))
                {
                    AppendElement(builder, "Lifecycle", row.Lifecycle!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.ModelName))
                {
                    AppendElement(builder, "ModelName", row.ModelName!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.Summary))
                {
                    AppendElement(builder, "Summary", row.Summary!, "      ");
                }
                if (!string.IsNullOrWhiteSpace(row.WorkspaceKind))
                {
                    AppendElement(builder, "WorkspaceKind", row.WorkspaceKind!, "      ");
                }
                builder.Append("    </WorkspaceInstance>\n");
            }
            builder.Append("  </WorkspaceInstanceList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadWorkspaceLinkList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceLinkList");
                return;
            }

            reader.ReadStartElement("WorkspaceLinkList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "WorkspaceLink", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'WorkspaceLinkList'.");
                }
                var row = ReadWorkspaceLink(reader, relationshipBuffers);
                loadState.AddWorkspaceLinkId(row.Id);
                model.WorkspaceLinkList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static WorkspaceLink ReadWorkspaceLink(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new WorkspaceLink();
            var relationships = new WorkspaceLinkRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FromWorkspaceId":
                            relationships.FromWorkspaceId = reader.Value;
                            break;
                        case "MeshId":
                            relationships.MeshId = reader.Value;
                            break;
                        case "ToWorkspaceId":
                            relationships.ToWorkspaceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'WorkspaceLink'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceLink");
                (relationshipBuffers.WorkspaceLinkRelationships ??= new List<WorkspaceLinkRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("WorkspaceLink");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Description":
                        row.Description = reader.ReadElementContentAsString();
                        break;
                    case "Kind":
                        row.Kind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'WorkspaceLink'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.WorkspaceLinkRelationships ??= new List<WorkspaceLinkRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeWorkspaceLinkShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <WorkspaceLinkList>\n");
            foreach (var row in model.WorkspaceLinkList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'WorkspaceLink' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'WorkspaceLink' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <WorkspaceLink Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var fromWorkspaceId = RequireIdentity(row.FromWorkspace?.Id, $"Relationship 'WorkspaceLink.FromWorkspaceId' on row 'WorkspaceLink:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceInstanceListById.TryGetValue(fromWorkspaceId, out var fromWorkspaceCanonical) || !ReferenceEquals(fromWorkspaceCanonical, row.FromWorkspace))
                {
                    throw new InvalidOperationException($"Relationship 'WorkspaceLink.FromWorkspaceId' on row 'WorkspaceLink:{row.Id}' references an object that is not the canonical row for Id '{fromWorkspaceId}'.");
                }
                builder.Append(' ');
                builder.Append("FromWorkspaceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, fromWorkspaceId);
                builder.Append('"');
                var meshId = RequireIdentity(row.Mesh?.Id, $"Relationship 'WorkspaceLink.MeshId' on row 'WorkspaceLink:{row.Id}' is empty.");
                if (!saveIndexes.MeshListById.TryGetValue(meshId, out var meshCanonical) || !ReferenceEquals(meshCanonical, row.Mesh))
                {
                    throw new InvalidOperationException($"Relationship 'WorkspaceLink.MeshId' on row 'WorkspaceLink:{row.Id}' references an object that is not the canonical row for Id '{meshId}'.");
                }
                builder.Append(' ');
                builder.Append("MeshId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, meshId);
                builder.Append('"');
                var toWorkspaceId = RequireIdentity(row.ToWorkspace?.Id, $"Relationship 'WorkspaceLink.ToWorkspaceId' on row 'WorkspaceLink:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceInstanceListById.TryGetValue(toWorkspaceId, out var toWorkspaceCanonical) || !ReferenceEquals(toWorkspaceCanonical, row.ToWorkspace))
                {
                    throw new InvalidOperationException($"Relationship 'WorkspaceLink.ToWorkspaceId' on row 'WorkspaceLink:{row.Id}' references an object that is not the canonical row for Id '{toWorkspaceId}'.");
                }
                builder.Append(' ');
                builder.Append("ToWorkspaceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, toWorkspaceId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.Description))
                {
                    AppendElement(builder, "Description", row.Description!, "      ");
                }
                AppendElement(builder, "Kind", RequireText(row.Kind, $"Entity 'WorkspaceLink' row '{row.Id}' is missing required property 'Kind'."), "      ");
                builder.Append("    </WorkspaceLink>\n");
            }
            builder.Append("  </WorkspaceLinkList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadWorkspaceMountList(MetaMeshModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceMountList");
                return;
            }

            reader.ReadStartElement("WorkspaceMountList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "WorkspaceMount", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'WorkspaceMountList'.");
                }
                var row = ReadWorkspaceMount(reader, relationshipBuffers);
                loadState.AddWorkspaceMountId(row.Id);
                model.WorkspaceMountList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static WorkspaceMount ReadWorkspaceMount(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new WorkspaceMount();
            var relationships = new WorkspaceMountRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "WorkspaceInstanceId":
                            relationships.WorkspaceInstanceId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'WorkspaceMount'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("WorkspaceMount");
                (relationshipBuffers.WorkspaceMountRelationships ??= new List<WorkspaceMountRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("WorkspaceMount");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "PathKind":
                        row.PathKind = reader.ReadElementContentAsString();
                        break;
                    case "PhysicalPath":
                        row.PhysicalPath = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'WorkspaceMount'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.WorkspaceMountRelationships ??= new List<WorkspaceMountRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeWorkspaceMountShard(MetaMeshModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.Ordinal);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaMesh>\n");
            builder.Append("  <WorkspaceMountList>\n");
            foreach (var row in model.WorkspaceMountList)
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'WorkspaceMount' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'WorkspaceMount' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <WorkspaceMount Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var workspaceInstanceId = RequireIdentity(row.WorkspaceInstance?.Id, $"Relationship 'WorkspaceMount.WorkspaceInstanceId' on row 'WorkspaceMount:{row.Id}' is empty.");
                if (!saveIndexes.WorkspaceInstanceListById.TryGetValue(workspaceInstanceId, out var workspaceInstanceCanonical) || !ReferenceEquals(workspaceInstanceCanonical, row.WorkspaceInstance))
                {
                    throw new InvalidOperationException($"Relationship 'WorkspaceMount.WorkspaceInstanceId' on row 'WorkspaceMount:{row.Id}' references an object that is not the canonical row for Id '{workspaceInstanceId}'.");
                }
                builder.Append(' ');
                builder.Append("WorkspaceInstanceId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, workspaceInstanceId);
                builder.Append('"');
                builder.Append(">\n");
                if (!string.IsNullOrWhiteSpace(row.PathKind))
                {
                    AppendElement(builder, "PathKind", row.PathKind!, "      ");
                }
                AppendElement(builder, "PhysicalPath", RequireText(row.PhysicalPath, $"Entity 'WorkspaceMount' row '{row.Id}' is missing required property 'PhysicalPath'."), "      ");
                builder.Append("    </WorkspaceMount>\n");
            }
            builder.Append("  </WorkspaceMountList>\n");
            builder.Append("</MetaMesh>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private sealed class MeshSuggestionRelationships
        {
            public MeshSuggestion Row { get; set; } = null!;
            public string MeshId { get; set; } = string.Empty;
            public string WorkspaceInstanceId { get; set; } = string.Empty;
        }

        private sealed class ModelProviderRelationships
        {
            public ModelProvider Row { get; set; } = null!;
            public string MeshId { get; set; } = string.Empty;
        }

        private sealed class OperationCapabilityRelationships
        {
            public OperationCapability Row { get; set; } = null!;
            public string ModelProviderId { get; set; } = string.Empty;
        }

        private sealed class OperationEffectRelationships
        {
            public OperationEffect Row { get; set; } = null!;
            public string OperationCapabilityId { get; set; } = string.Empty;
        }

        private sealed class ProviderBindingRelationships
        {
            public ProviderBinding Row { get; set; } = null!;
            public string ModelProviderId { get; set; } = string.Empty;
            public string WorkspaceInstanceId { get; set; } = string.Empty;
        }

        private sealed class WorkspaceInstanceRelationships
        {
            public WorkspaceInstance Row { get; set; } = null!;
            public string MeshId { get; set; } = string.Empty;
        }

        private sealed class WorkspaceLinkRelationships
        {
            public WorkspaceLink Row { get; set; } = null!;
            public string FromWorkspaceId { get; set; } = string.Empty;
            public string MeshId { get; set; } = string.Empty;
            public string ToWorkspaceId { get; set; } = string.Empty;
        }

        private sealed class WorkspaceMountRelationships
        {
            public WorkspaceMount Row { get; set; } = null!;
            public string WorkspaceInstanceId { get; set; } = string.Empty;
        }

        private sealed class RelationshipBuffers
        {
            public List<MeshSuggestionRelationships>? MeshSuggestionRelationships { get; set; }
            public List<ModelProviderRelationships>? ModelProviderRelationships { get; set; }
            public List<OperationCapabilityRelationships>? OperationCapabilityRelationships { get; set; }
            public List<OperationEffectRelationships>? OperationEffectRelationships { get; set; }
            public List<ProviderBindingRelationships>? ProviderBindingRelationships { get; set; }
            public List<WorkspaceInstanceRelationships>? WorkspaceInstanceRelationships { get; set; }
            public List<WorkspaceLinkRelationships>? WorkspaceLinkRelationships { get; set; }
            public List<WorkspaceMountRelationships>? WorkspaceMountRelationships { get; set; }
        }

        private static void ResolveRelationshipGroup1(LoadIndexes loadIndexes, RelationshipBuffers relationshipBuffers)
        {
            foreach (var relationship in relationshipBuffers.MeshSuggestionRelationships ?? Enumerable.Empty<MeshSuggestionRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "MeshSuggestion",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.MeshSuggestionRelationships ?? Enumerable.Empty<MeshSuggestionRelationships>())
            {
                relationship.Row.WorkspaceInstance = string.IsNullOrWhiteSpace(relationship.WorkspaceInstanceId)
                    ? null
                    : RequireTarget(
                        loadIndexes.WorkspaceInstanceListById,
                        relationship.WorkspaceInstanceId,
                        "MeshSuggestion",
                        relationship.Row.Id,
                        "WorkspaceInstanceId");
            }

            foreach (var relationship in relationshipBuffers.ModelProviderRelationships ?? Enumerable.Empty<ModelProviderRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "ModelProvider",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.OperationCapabilityRelationships ?? Enumerable.Empty<OperationCapabilityRelationships>())
            {
                relationship.Row.ModelProvider = RequireTarget(
                    loadIndexes.ModelProviderListById,
                    relationship.ModelProviderId,
                    "OperationCapability",
                    relationship.Row.Id,
                    "ModelProviderId");
            }

            foreach (var relationship in relationshipBuffers.OperationEffectRelationships ?? Enumerable.Empty<OperationEffectRelationships>())
            {
                relationship.Row.OperationCapability = RequireTarget(
                    loadIndexes.OperationCapabilityListById,
                    relationship.OperationCapabilityId,
                    "OperationEffect",
                    relationship.Row.Id,
                    "OperationCapabilityId");
            }

            foreach (var relationship in relationshipBuffers.ProviderBindingRelationships ?? Enumerable.Empty<ProviderBindingRelationships>())
            {
                relationship.Row.ModelProvider = RequireTarget(
                    loadIndexes.ModelProviderListById,
                    relationship.ModelProviderId,
                    "ProviderBinding",
                    relationship.Row.Id,
                    "ModelProviderId");
            }

            foreach (var relationship in relationshipBuffers.ProviderBindingRelationships ?? Enumerable.Empty<ProviderBindingRelationships>())
            {
                relationship.Row.WorkspaceInstance = RequireTarget(
                    loadIndexes.WorkspaceInstanceListById,
                    relationship.WorkspaceInstanceId,
                    "ProviderBinding",
                    relationship.Row.Id,
                    "WorkspaceInstanceId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceInstanceRelationships ?? Enumerable.Empty<WorkspaceInstanceRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "WorkspaceInstance",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceLinkRelationships ?? Enumerable.Empty<WorkspaceLinkRelationships>())
            {
                relationship.Row.FromWorkspace = RequireTarget(
                    loadIndexes.WorkspaceInstanceListById,
                    relationship.FromWorkspaceId,
                    "WorkspaceLink",
                    relationship.Row.Id,
                    "FromWorkspaceId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceLinkRelationships ?? Enumerable.Empty<WorkspaceLinkRelationships>())
            {
                relationship.Row.Mesh = RequireTarget(
                    loadIndexes.MeshListById,
                    relationship.MeshId,
                    "WorkspaceLink",
                    relationship.Row.Id,
                    "MeshId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceLinkRelationships ?? Enumerable.Empty<WorkspaceLinkRelationships>())
            {
                relationship.Row.ToWorkspace = RequireTarget(
                    loadIndexes.WorkspaceInstanceListById,
                    relationship.ToWorkspaceId,
                    "WorkspaceLink",
                    relationship.Row.Id,
                    "ToWorkspaceId");
            }

            foreach (var relationship in relationshipBuffers.WorkspaceMountRelationships ?? Enumerable.Empty<WorkspaceMountRelationships>())
            {
                relationship.Row.WorkspaceInstance = RequireTarget(
                    loadIndexes.WorkspaceInstanceListById,
                    relationship.WorkspaceInstanceId,
                    "WorkspaceMount",
                    relationship.Row.Id,
                    "WorkspaceInstanceId");
            }

        }

        private static readonly string[] ShardFileNames =
        {
            "Mesh.xml",
            "MeshSuggestion.xml",
            "ModelProvider.xml",
            "OperationCapability.xml",
            "OperationEffect.xml",
            "ProviderBinding.xml",
            "WorkspaceInstance.xml",
            "WorkspaceLink.xml",
            "WorkspaceMount.xml",
        };

        private static HashSet<string> BuildExpectedShardPaths(string instanceDirectoryPath)
        {
            var expectedShardPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var shardFileName in ShardFileNames)
            {
                expectedShardPaths.Add(Path.GetFullPath(Path.Combine(instanceDirectoryPath, shardFileName)));
            }

            return expectedShardPaths;
        }

        private sealed class LoadState
        {
            private HashSet<string>? meshIds;

            public void AddMeshId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Mesh' contains a row with empty Id.");
                meshIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!meshIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Mesh' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? meshSuggestionIds;

            public void AddMeshSuggestionId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'MeshSuggestion' contains a row with empty Id.");
                meshSuggestionIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!meshSuggestionIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'MeshSuggestion' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? modelProviderIds;

            public void AddModelProviderId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'ModelProvider' contains a row with empty Id.");
                modelProviderIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!modelProviderIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'ModelProvider' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? operationCapabilityIds;

            public void AddOperationCapabilityId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'OperationCapability' contains a row with empty Id.");
                operationCapabilityIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!operationCapabilityIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'OperationCapability' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? operationEffectIds;

            public void AddOperationEffectId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'OperationEffect' contains a row with empty Id.");
                operationEffectIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!operationEffectIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'OperationEffect' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? providerBindingIds;

            public void AddProviderBindingId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'ProviderBinding' contains a row with empty Id.");
                providerBindingIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!providerBindingIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'ProviderBinding' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? workspaceInstanceIds;

            public void AddWorkspaceInstanceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'WorkspaceInstance' contains a row with empty Id.");
                workspaceInstanceIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!workspaceInstanceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'WorkspaceInstance' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? workspaceLinkIds;

            public void AddWorkspaceLinkId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'WorkspaceLink' contains a row with empty Id.");
                workspaceLinkIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!workspaceLinkIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'WorkspaceLink' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? workspaceMountIds;

            public void AddWorkspaceMountId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'WorkspaceMount' contains a row with empty Id.");
                workspaceMountIds ??= new HashSet<string>(StringComparer.Ordinal);
                if (!workspaceMountIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'WorkspaceMount' contains duplicate Id '{normalizedId}'.");
                }
            }

        }

        private sealed class LoadIndexes
        {
            private readonly MetaMeshModel model;

            public LoadIndexes(MetaMeshModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Mesh>? meshListById;

            public Dictionary<string, Mesh> MeshListById => meshListById ??= BuildById(model.MeshList, row => row.Id, "Mesh");

            private Dictionary<string, MeshSuggestion>? meshSuggestionListById;

            public Dictionary<string, MeshSuggestion> MeshSuggestionListById => meshSuggestionListById ??= BuildById(model.MeshSuggestionList, row => row.Id, "MeshSuggestion");

            private Dictionary<string, ModelProvider>? modelProviderListById;

            public Dictionary<string, ModelProvider> ModelProviderListById => modelProviderListById ??= BuildById(model.ModelProviderList, row => row.Id, "ModelProvider");

            private Dictionary<string, OperationCapability>? operationCapabilityListById;

            public Dictionary<string, OperationCapability> OperationCapabilityListById => operationCapabilityListById ??= BuildById(model.OperationCapabilityList, row => row.Id, "OperationCapability");

            private Dictionary<string, OperationEffect>? operationEffectListById;

            public Dictionary<string, OperationEffect> OperationEffectListById => operationEffectListById ??= BuildById(model.OperationEffectList, row => row.Id, "OperationEffect");

            private Dictionary<string, ProviderBinding>? providerBindingListById;

            public Dictionary<string, ProviderBinding> ProviderBindingListById => providerBindingListById ??= BuildById(model.ProviderBindingList, row => row.Id, "ProviderBinding");

            private Dictionary<string, WorkspaceInstance>? workspaceInstanceListById;

            public Dictionary<string, WorkspaceInstance> WorkspaceInstanceListById => workspaceInstanceListById ??= BuildById(model.WorkspaceInstanceList, row => row.Id, "WorkspaceInstance");

            private Dictionary<string, WorkspaceLink>? workspaceLinkListById;

            public Dictionary<string, WorkspaceLink> WorkspaceLinkListById => workspaceLinkListById ??= BuildById(model.WorkspaceLinkList, row => row.Id, "WorkspaceLink");

            private Dictionary<string, WorkspaceMount>? workspaceMountListById;

            public Dictionary<string, WorkspaceMount> WorkspaceMountListById => workspaceMountListById ??= BuildById(model.WorkspaceMountList, row => row.Id, "WorkspaceMount");

        }

        private sealed class SaveIndexes
        {
            private readonly MetaMeshModel model;

            public SaveIndexes(MetaMeshModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Mesh>? meshListById;

            public Dictionary<string, Mesh> MeshListById => meshListById ??= BuildById(model.MeshList, row => row.Id, "Mesh");

            private Dictionary<string, MeshSuggestion>? meshSuggestionListById;

            public Dictionary<string, MeshSuggestion> MeshSuggestionListById => meshSuggestionListById ??= BuildById(model.MeshSuggestionList, row => row.Id, "MeshSuggestion");

            private Dictionary<string, ModelProvider>? modelProviderListById;

            public Dictionary<string, ModelProvider> ModelProviderListById => modelProviderListById ??= BuildById(model.ModelProviderList, row => row.Id, "ModelProvider");

            private Dictionary<string, OperationCapability>? operationCapabilityListById;

            public Dictionary<string, OperationCapability> OperationCapabilityListById => operationCapabilityListById ??= BuildById(model.OperationCapabilityList, row => row.Id, "OperationCapability");

            private Dictionary<string, OperationEffect>? operationEffectListById;

            public Dictionary<string, OperationEffect> OperationEffectListById => operationEffectListById ??= BuildById(model.OperationEffectList, row => row.Id, "OperationEffect");

            private Dictionary<string, ProviderBinding>? providerBindingListById;

            public Dictionary<string, ProviderBinding> ProviderBindingListById => providerBindingListById ??= BuildById(model.ProviderBindingList, row => row.Id, "ProviderBinding");

            private Dictionary<string, WorkspaceInstance>? workspaceInstanceListById;

            public Dictionary<string, WorkspaceInstance> WorkspaceInstanceListById => workspaceInstanceListById ??= BuildById(model.WorkspaceInstanceList, row => row.Id, "WorkspaceInstance");

            private Dictionary<string, WorkspaceLink>? workspaceLinkListById;

            public Dictionary<string, WorkspaceLink> WorkspaceLinkListById => workspaceLinkListById ??= BuildById(model.WorkspaceLinkList, row => row.Id, "WorkspaceLink");

            private Dictionary<string, WorkspaceMount>? workspaceMountListById;

            public Dictionary<string, WorkspaceMount> WorkspaceMountListById => workspaceMountListById ??= BuildById(model.WorkspaceMountList, row => row.Id, "WorkspaceMount");

        }

        private static readonly Lazy<bool> RuntimeExtendedShape = new(DetectRuntimeExtendedShape);

        private static bool HasRuntimeExtendedShape()
        {
            return RuntimeExtendedShape.Value;
        }

        private static bool DetectRuntimeExtendedShape()
        {
            if (HasRuntimeExtendedEntityShapeGroup1())
            {
                return true;
            }

            return HasUnexpectedModelLists();
        }

        private static bool HasRuntimeExtendedEntityShapeGroup1()
        {
            if (HasUnexpectedProperties(typeof(Mesh),
                "Id",
                "Description",
                "Name",
                "RootPath"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(MeshSuggestion),
                "Id",
                "Message",
                "Severity",
                "SuggestedHandle",
                "SuggestedLifecycle",
                "SuggestedPath",
                "SuggestedWorkspaceKind",
                "SuggestionKind",
                "WorkspaceHandle",
                "Mesh",
                "WorkspaceInstance"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(ModelProvider),
                "Id",
                "Description",
                "ExecutableName",
                "Name",
                "ProviderKind",
                "Mesh"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(OperationCapability),
                "Id",
                "CanHandleHostRequest",
                "Description",
                "Name",
                "ModelProvider"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(OperationEffect),
                "Id",
                "EffectKind",
                "OperationCapability"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(ProviderBinding),
                "Id",
                "SupportedModelName",
                "ModelProvider",
                "WorkspaceInstance"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(WorkspaceInstance),
                "Id",
                "DisplayName",
                "Handle",
                "Lifecycle",
                "ModelName",
                "Summary",
                "WorkspaceKind",
                "Mesh"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(WorkspaceLink),
                "Id",
                "Description",
                "Kind",
                "FromWorkspace",
                "Mesh",
                "ToWorkspace"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(WorkspaceMount),
                "Id",
                "PathKind",
                "PhysicalPath",
                "WorkspaceInstance"))
            {
                return true;
            }

            return false;
        }

        private static bool HasUnexpectedModelLists()
        {
            var knownLists = new HashSet<string>(StringComparer.Ordinal)
            {
                "MeshList",
                "MeshSuggestionList",
                "ModelProviderList",
                "OperationCapabilityList",
                "OperationEffectList",
                "ProviderBindingList",
                "WorkspaceInstanceList",
                "WorkspaceLinkList",
                "WorkspaceMountList",
            };
            return typeof(MetaMeshModel).GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Any(property =>
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(List<>) &&
                    !knownLists.Contains(property.Name));
        }

        private static bool HasUnexpectedProperties(Type type, params string[] knownProperties)
        {
            return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanRead && property.CanWrite && property.GetIndexParameters().Length == 0)
                .Any(property => !knownProperties.Contains(property.Name, StringComparer.Ordinal));
        }

        private static Dictionary<string, T> BuildById<T>(IEnumerable<T> rows, Func<T, string> getId, string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.Ordinal);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }
            return rowsById;
        }

        private static T RequireTarget<T>(Dictionary<string, T> rowsById, string targetId, string sourceEntityName, string sourceId, string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidDataException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }
            return target;
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var normalizedValue = value?.Trim() ?? string.Empty;
            if (string.IsNullOrEmpty(normalizedValue))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return normalizedValue;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return value;
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string indent)
        {
            builder.Append(indent);
            builder.Append('<');
            builder.Append(name);
            builder.Append('>');
            AppendXmlText(builder, value);
            builder.Append("</");
            builder.Append(name);
            builder.Append(">\n");
        }

        private static void AppendXmlAttribute(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    case '"': builder.Append("&quot;"); break;
                    case '\'': builder.Append("&apos;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static void AppendXmlText(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static bool IsNamespaceDeclaration(XmlReader reader)
        {
            return string.Equals(reader.Prefix, "xmlns", StringComparison.Ordinal) ||
                   string.Equals(reader.LocalName, "xmlns", StringComparison.Ordinal);
        }

        private static void DeleteIfExists(string path)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

    }

}
