// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

using Meta.Core.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MetaMesh
{
    public static class MetaMeshTooling
    {
        public static MetaMeshModel Load(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaMeshModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaMeshModel> LoadAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaMeshModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static string CreateWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.CreateWorkspace<MetaMeshModel>(workspacePath);
        }

        public static bool IsWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.IsWorkspace<MetaMeshModel>(workspacePath);
        }

        public static void Save(MetaMeshModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaMeshModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
