// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class OperationEffect
    {
        public string Id { get; set; } = string.Empty;

        public string EffectKind { get; set; } = string.Empty;

        public OperationCapability OperationCapability { get; set; } = null!;

    }
}
