// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class OperationCapability
    {
        public string Id { get; set; } = string.Empty;

        public string? CanHandleHostRequest { get; set; }

        public string? Description { get; set; }

        public string Name { get; set; } = string.Empty;

        public ModelProvider ModelProvider { get; set; } = null!;

    }
}
