// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class OperationStep
    {
        public string Id { get; set; } = string.Empty;

        public string? Arguments { get; set; }

        public string? Description { get; set; }

        public string Executable { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string? WorkingDirectory { get; set; }

        public Operation Operation { get; set; } = null!;

        public OperationStep? PreviousStep { get; set; }

    }
}
