// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class WorkspaceMount
    {
        public string Id { get; set; } = string.Empty;

        public string? PathKind { get; set; }

        public string PhysicalPath { get; set; } = string.Empty;

        public WorkspaceInstance WorkspaceInstance { get; set; } = null!;

    }
}
