// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class WorkspaceLink
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string Kind { get; set; } = string.Empty;

        public WorkspaceInstance FromWorkspace { get; set; } = null!;

        public Mesh Mesh { get; set; } = null!;

        public WorkspaceInstance ToWorkspace { get; set; } = null!;

    }
}
