// <auto-generated>
// This file was generated by Meta.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMesh
{
    public sealed class XmlWorkspace
    {
        public string Id { get; set; } = string.Empty;

        public string Path { get; set; } = string.Empty;

        public Workspace Workspace { get; set; } = null!;

    }
}
