using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Meta.Core.Domain;

namespace Meta.Core.Services;

public static partial class GenerationService
{
    private static readonly HashSet<string> CSharpKeywords = new(
        new[]
        {
            "abstract", "add", "alias", "and", "as", "ascending", "async",
            "await", "base", "bool", "break", "by", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal",
            "default", "delegate", "descending", "do", "double", "dynamic",
            "else", "enum", "equals", "event", "explicit", "extern", "false",
            "file", "finally", "fixed", "float", "for", "foreach", "from",
            "get", "global", "goto", "group", "if", "implicit", "in", "init",
            "int", "interface", "internal", "into", "is", "join", "let", "lock",
            "long", "managed", "nameof", "namespace", "new", "nint", "not",
            "notnull", "nuint", "null", "object", "on", "operator", "or",
            "orderby", "out", "override", "params", "partial", "private",
            "protected", "public", "readonly", "record", "ref", "remove",
            "required", "return", "sbyte", "scoped", "sealed", "select", "set",
            "short", "sizeof", "stackalloc", "static", "string", "struct",
            "switch", "this", "throw", "true", "try", "typeof", "uint",
            "ulong", "unchecked", "unmanaged", "unsafe", "ushort", "using",
            "value", "var", "virtual", "void", "volatile", "when", "where",
            "while", "with", "yield",
        },
        StringComparer.Ordinal);

    private static void AppendGeneratedCSharpHeader(StringBuilder builder, bool requiresTooling, string? workspacePath)
    {
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// This file was generated by Meta.");
        builder.AppendLine("// Do not edit this file by hand.");
        if (requiresTooling ||
            !string.IsNullOrWhiteSpace(workspacePath))
        {
            var displayWorkspacePath = GetDisplayWorkspacePath(
                workspacePath);
            var regenerationCommand = requiresTooling
                ? $"meta generate csharp --workspace {QuoteForShellComment(displayWorkspacePath)} --out <dir> --tooling"
                : $"meta generate csharp --workspace {QuoteForShellComment(displayWorkspacePath)} --out <dir>";
            builder.AppendLine("//");
            builder.AppendLine(
                $"// Source workspace: {displayWorkspacePath}");
            builder.AppendLine("// Regenerate with:");
            builder.AppendLine($"//   {regenerationCommand}");
        }

        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
    }

    private static string GetDisplayWorkspacePath(string? workspacePath)
    {
        if (string.IsNullOrWhiteSpace(workspacePath))
        {
            return ".\\<workspace>";
        }

        var trimmedPath = workspacePath
            .Trim()
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var leafName = Path.GetFileName(trimmedPath);
        return string.IsNullOrWhiteSpace(leafName)
            ? ".\\<workspace>"
            : $".\\{leafName}";
    }

    private static string QuoteForShellComment(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "\"\"";
        }

        return "\"" + value.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
    }

    private static string ResolveModelNamespaceName(string? modelName)
    {
        return string.IsNullOrWhiteSpace(modelName) ? "MetadataModel" : modelName.Trim();
    }

    private static string ResolveConsumerModelTypeName(GenericModel model)
    {
        var baseName = ResolveModelNamespaceName(model.Name);
        var entityNames = model.Entities
            .Where(entity => !string.IsNullOrWhiteSpace(entity.Name))
            .Select(entity => entity.Name.Trim())
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        if (!entityNames.Contains(baseName))
        {
            return baseName;
        }

        var candidate = baseName + "Model";
        var suffix = 2;
        while (entityNames.Contains(candidate))
        {
            candidate = baseName + "Model" + suffix.ToString(CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string ResolveToolingModelTypeName(GenericModel model)
    {
        var baseName = ResolveModelNamespaceName(model.Name) + "Model";
        var entityNames = model.Entities
            .Where(entity => !string.IsNullOrWhiteSpace(entity.Name))
            .Select(entity => entity.Name.Trim())
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (!entityNames.Contains(baseName))
        {
            return baseName;
        }

        var candidate = baseName + "2";
        var suffix = 3;
        while (entityNames.Contains(candidate))
        {
            candidate = baseName + suffix.ToString(CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string BuildModelXml(GenericModel model)
    {
        var document = Meta.Core.Serialization.ModelXmlCodec.BuildDocument(model);
        return document.ToString(global::System.Xml.Linq.SaveOptions.None);
    }

    private static string ToCSharpStringLiteral(string? value)
    {
        if (value == null)
        {
            return "\"\"";
        }

        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string ToCamelIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "value";
        }

        if (name.Length == 1)
        {
            return char.ToLowerInvariant(name[0]).ToString();
        }

        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private static string ToCSharpIdentifier(string name)
    {
        return CSharpKeywords.Contains(name)
            ? "@" + name
            : name;
    }

    private static string ToPascalIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "Value";
        }

        if (name.Length == 1)
        {
            return char.ToUpperInvariant(name[0]).ToString();
        }

        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private static string NormalizeNewlines(string value)
    {
        return value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace("\r", "\n", StringComparison.Ordinal);
    }
}
