// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationExample
    {
        public string Id { get; set; } = string.Empty;

        public string Origin { get; set; } = string.Empty;

        public string ReviewStatus { get; set; } = string.Empty;

        public string? Summary { get; set; }

        public string Title { get; set; } = string.Empty;

        public DocumentationSubject DocumentationSubject { get; set; } = null!;

        public DocumentationExample? PreviousExample { get; set; }

    }
}
