// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationExampleSection
    {
        public string Id { get; set; } = string.Empty;

        public string? Body { get; set; }

        public string BodyFormat { get; set; } = string.Empty;

        public string? Title { get; set; }

        public DocumentationExample DocumentationExample { get; set; } = null!;

        public DocumentationExampleSection? PreviousSection { get; set; }

    }
}
