// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationViewNode
    {
        public string Id { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string? ParentNodeId { get; set; }

        public string? Selection { get; set; }

        public string? SubjectKey { get; set; }

        public string Title { get; set; } = string.Empty;

        public DocumentationView DocumentationView { get; set; } = null!;

    }
}
