// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationEntityImportSpec
    {
        public string Id { get; set; } = string.Empty;

        public string? DisplayNameProperty { get; set; }

        public string EntityName { get; set; } = string.Empty;

        public string IncludeInstances { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string ReviewStatus { get; set; } = string.Empty;

        public string? SummaryProperty { get; set; }

        public DocumentationInstanceImportSpec DocumentationInstanceImportSpec { get; set; } = null!;

    }
}
