// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationExampleCode
    {
        public string Id { get; set; } = string.Empty;

        public string Code { get; set; } = string.Empty;

        public string? Language { get; set; }

        public string? Title { get; set; }

        public DocumentationExampleSection DocumentationExampleSection { get; set; } = null!;

        public DocumentationExampleCode? PreviousCode { get; set; }

    }
}
