// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationFact
    {
        public string Id { get; set; } = string.Empty;

        public string Kind { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string? SourceFingerprint { get; set; }

        public string Status { get; set; } = string.Empty;

        public string SubjectKey { get; set; } = string.Empty;

        public string? Value { get; set; }

        public string ValueKind { get; set; } = string.Empty;

        public DocumentationImportBatch DocumentationImportBatch { get; set; } = null!;

        public DocumentationSource DocumentationSource { get; set; } = null!;

        public DocumentationSubject DocumentationSubject { get; set; } = null!;

    }
}
