// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationNarrative
    {
        public string Id { get; set; } = string.Empty;

        public string? Body { get; set; }

        public string BodyFormat { get; set; } = string.Empty;

        public string? LastReviewedImportBatchId { get; set; }

        public string Ordinal { get; set; } = string.Empty;

        public string Origin { get; set; } = string.Empty;

        public string ReviewStatus { get; set; } = string.Empty;

        public string Slot { get; set; } = string.Empty;

        public string SubjectKey { get; set; } = string.Empty;

        public string? Title { get; set; }

        public DocumentationSubject DocumentationSubject { get; set; } = null!;

    }
}
