// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationTemplate
    {
        public string Id { get; set; } = string.Empty;

        public string? Html { get; set; }

        public string Kind { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string? SourceUrl { get; set; }

        public DocumentationTheme DocumentationTheme { get; set; } = null!;

        public DocumentationTemplate? PreviousTemplate { get; set; }

    }
}
