// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationSubject
    {
        public string Id { get; set; } = string.Empty;

        public string DisplayName { get; set; } = string.Empty;

        public string? DisplayPath { get; set; }

        public string Key { get; set; } = string.Empty;

        public string Kind { get; set; } = string.Empty;

        public string? NativeId { get; set; }

        public string? NativeKind { get; set; }

        public string Ordinal { get; set; } = string.Empty;

        public string? ParentKey { get; set; }

        public string Status { get; set; } = string.Empty;

        public string? Summary { get; set; }

        public DocumentationSource DocumentationSource { get; set; } = null!;

    }
}
