// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDocs
{
    public sealed class DocumentationSubjectAlias
    {
        public string Id { get; set; } = string.Empty;

        public string Alias { get; set; } = string.Empty;

        public string? Reason { get; set; }

        public DocumentationSubject DocumentationSubject { get; set; } = null!;

    }
}
