// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Meta.Core.Serialization;

namespace MetaWeave
{
    public sealed partial class MetaWeaveModel : IMetaWorkspaceModel<MetaWeaveModel>
    {
        public static MetaWeaveModel CreateEmpty() => new();

        public List<ModelReference> ModelReferenceList { get; set; } = new();

        public List<PropertyBinding> PropertyBindingList { get; set; } = new();

        public static MetaWeaveModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaWeaveModelXmlSerializer.Load(workspacePath, searchUpward);
        }

        public static Task<MetaWeaveModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaWeaveModelXmlSerializer.Save(this, workspacePath);
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }

    internal static class MetaWeaveModelXmlSerializer
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        internal static MetaWeaveModel Load(string workspacePath, bool searchUpward)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (searchUpward)
            {
                throw new NotSupportedException("Typed workspace loading does not search parent directories. Pass an explicit workspace path.");
            }

            if (HasRuntimeExtendedShape())
            {
                return TypedWorkspaceXmlSerializer.Load<MetaWeaveModel>(workspacePath, searchUpward);
            }

            var workspaceRootPath = TypedWorkspaceXmlSerializer.RequireWorkspace<MetaWeaveModel>(workspacePath);

            var model = new MetaWeaveModel();
            var loadState = new LoadState();
            var relationshipBuffers = new RelationshipBuffers();
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            if (!Directory.Exists(instanceDirectoryPath))
            {
                return model;
            }

            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                LoadShard(model, shardPath, loadState, relationshipBuffers);
            }

            var loadIndexes = new LoadIndexes(model);
            ResolveRelationshipGroup1(loadIndexes, relationshipBuffers);
            return model;
        }

        internal static void Save(MetaWeaveModel model, string workspacePath)
        {
            ArgumentNullException.ThrowIfNull(model);
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (HasRuntimeExtendedShape())
            {
                TypedWorkspaceXmlSerializer.Save(model, workspacePath);
                return;
            }

            TypedWorkspaceXmlSerializer.SaveModel(model, workspacePath);

            var saveIndexes = new SaveIndexes(model);

            var workspaceRootPath = Path.GetFullPath(workspacePath);
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            Directory.CreateDirectory(instanceDirectoryPath);
            var expectedShardPaths = BuildExpectedShardPaths(instanceDirectoryPath);
            SaveShardGroup1(model, instanceDirectoryPath, saveIndexes);
            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                if (!expectedShardPaths.Contains(Path.GetFullPath(shardPath)))
                {
                    File.Delete(shardPath);
                }
            }
        }

        private static void SaveShardGroup1(MetaWeaveModel model, string instanceDirectoryPath, SaveIndexes saveIndexes)
        {
            model.ModelReferenceList ??= new List<ModelReference>();
            var modelReferenceShardPath = Path.Combine(instanceDirectoryPath, "ModelReference.xml");
            if (model.ModelReferenceList.Count == 0)
            {
                DeleteIfExists(modelReferenceShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(modelReferenceShardPath, SerializeModelReferenceShard(model, saveIndexes));
            }

            model.PropertyBindingList ??= new List<PropertyBinding>();
            var propertyBindingShardPath = Path.Combine(instanceDirectoryPath, "PropertyBinding.xml");
            if (model.PropertyBindingList.Count == 0)
            {
                DeleteIfExists(propertyBindingShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(propertyBindingShardPath, SerializePropertyBindingShard(model, saveIndexes));
            }

        }

        private static void LoadShard(MetaWeaveModel model, string shardPath, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            using var reader = XmlReader.Create(shardPath, new XmlReaderSettings
            {
                IgnoreComments = true,
                IgnoreWhitespace = true,
            });
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element || !string.Equals(reader.LocalName, "MetaWeave", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"Instance XML '{shardPath}' root must be <MetaWeave>.");
            }
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return;
            }
            reader.ReadStartElement("MetaWeave");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "ModelReferenceList":
                        LoadModelReferenceList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "PropertyBindingList":
                        LoadPropertyBindingList(model, reader, loadState, relationshipBuffers);
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in '{shardPath}'.");
                }
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static void LoadModelReferenceList(MetaWeaveModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ModelReferenceList");
                return;
            }

            reader.ReadStartElement("ModelReferenceList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "ModelReference", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'ModelReferenceList'.");
                }
                var row = ReadModelReference(reader, relationshipBuffers);
                loadState.AddModelReferenceId(row.Id);
                model.ModelReferenceList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static ModelReference ReadModelReference(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new ModelReference();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'ModelReference'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("ModelReference");
                return row;
            }

            reader.ReadStartElement("ModelReference");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Alias":
                        row.Alias = reader.ReadElementContentAsString();
                        break;
                    case "ModelName":
                        row.ModelName = reader.ReadElementContentAsString();
                        break;
                    case "WorkspacePath":
                        row.WorkspacePath = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'ModelReference'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeModelReferenceShard(MetaWeaveModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaWeave>\n");
            builder.Append("  <ModelReferenceList>\n");
            foreach (var row in model.ModelReferenceList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'ModelReference' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'ModelReference' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <ModelReference Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Alias", RequireText(row.Alias, $"Entity 'ModelReference' row '{row.Id}' is missing required property 'Alias'."), "      ");
                AppendElement(builder, "ModelName", RequireText(row.ModelName, $"Entity 'ModelReference' row '{row.Id}' is missing required property 'ModelName'."), "      ");
                AppendElement(builder, "WorkspacePath", RequireText(row.WorkspacePath, $"Entity 'ModelReference' row '{row.Id}' is missing required property 'WorkspacePath'."), "      ");
                builder.Append("    </ModelReference>\n");
            }
            builder.Append("  </ModelReferenceList>\n");
            builder.Append("</MetaWeave>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadPropertyBindingList(MetaWeaveModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("PropertyBindingList");
                return;
            }

            reader.ReadStartElement("PropertyBindingList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "PropertyBinding", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'PropertyBindingList'.");
                }
                var row = ReadPropertyBinding(reader, relationshipBuffers);
                loadState.AddPropertyBindingId(row.Id);
                model.PropertyBindingList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static PropertyBinding ReadPropertyBinding(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new PropertyBinding();
            var relationships = new PropertyBindingRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "SourceModelId":
                            relationships.SourceModelId = reader.Value;
                            break;
                        case "TargetModelId":
                            relationships.TargetModelId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'PropertyBinding'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("PropertyBinding");
                (relationshipBuffers.PropertyBindingRelationships ??= new List<PropertyBindingRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("PropertyBinding");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "SourceEntity":
                        row.SourceEntity = reader.ReadElementContentAsString();
                        break;
                    case "SourceProperty":
                        row.SourceProperty = reader.ReadElementContentAsString();
                        break;
                    case "TargetEntity":
                        row.TargetEntity = reader.ReadElementContentAsString();
                        break;
                    case "TargetProperty":
                        row.TargetProperty = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'PropertyBinding'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.PropertyBindingRelationships ??= new List<PropertyBindingRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializePropertyBindingShard(MetaWeaveModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaWeave>\n");
            builder.Append("  <PropertyBindingList>\n");
            foreach (var row in model.PropertyBindingList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'PropertyBinding' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'PropertyBinding' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <PropertyBinding Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var sourceModelId = RequireIdentity(row.SourceModel?.Id, $"Relationship 'PropertyBinding.SourceModelId' on row 'PropertyBinding:{row.Id}' is empty.");
                if (!saveIndexes.ModelReferenceListById.TryGetValue(sourceModelId, out var sourceModelCanonical) || !ReferenceEquals(sourceModelCanonical, row.SourceModel))
                {
                    throw new InvalidOperationException($"Relationship 'PropertyBinding.SourceModelId' on row 'PropertyBinding:{row.Id}' references an object that is not the canonical row for Id '{sourceModelId}'.");
                }
                builder.Append(' ');
                builder.Append("SourceModelId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, sourceModelId);
                builder.Append('"');
                var targetModelId = RequireIdentity(row.TargetModel?.Id, $"Relationship 'PropertyBinding.TargetModelId' on row 'PropertyBinding:{row.Id}' is empty.");
                if (!saveIndexes.ModelReferenceListById.TryGetValue(targetModelId, out var targetModelCanonical) || !ReferenceEquals(targetModelCanonical, row.TargetModel))
                {
                    throw new InvalidOperationException($"Relationship 'PropertyBinding.TargetModelId' on row 'PropertyBinding:{row.Id}' references an object that is not the canonical row for Id '{targetModelId}'.");
                }
                builder.Append(' ');
                builder.Append("TargetModelId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, targetModelId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'PropertyBinding' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "SourceEntity", RequireText(row.SourceEntity, $"Entity 'PropertyBinding' row '{row.Id}' is missing required property 'SourceEntity'."), "      ");
                AppendElement(builder, "SourceProperty", RequireText(row.SourceProperty, $"Entity 'PropertyBinding' row '{row.Id}' is missing required property 'SourceProperty'."), "      ");
                AppendElement(builder, "TargetEntity", RequireText(row.TargetEntity, $"Entity 'PropertyBinding' row '{row.Id}' is missing required property 'TargetEntity'."), "      ");
                AppendElement(builder, "TargetProperty", RequireText(row.TargetProperty, $"Entity 'PropertyBinding' row '{row.Id}' is missing required property 'TargetProperty'."), "      ");
                builder.Append("    </PropertyBinding>\n");
            }
            builder.Append("  </PropertyBindingList>\n");
            builder.Append("</MetaWeave>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private sealed class PropertyBindingRelationships
        {
            public PropertyBinding Row { get; set; } = null!;
            public string SourceModelId { get; set; } = string.Empty;
            public string TargetModelId { get; set; } = string.Empty;
        }

        private sealed class RelationshipBuffers
        {
            public List<PropertyBindingRelationships>? PropertyBindingRelationships { get; set; }
        }

        private static void ResolveRelationshipGroup1(LoadIndexes loadIndexes, RelationshipBuffers relationshipBuffers)
        {
            foreach (var relationship in relationshipBuffers.PropertyBindingRelationships ?? Enumerable.Empty<PropertyBindingRelationships>())
            {
                relationship.Row.SourceModel = RequireTarget(
                    loadIndexes.ModelReferenceListById,
                    relationship.SourceModelId,
                    "PropertyBinding",
                    relationship.Row.Id,
                    "SourceModelId");
            }

            foreach (var relationship in relationshipBuffers.PropertyBindingRelationships ?? Enumerable.Empty<PropertyBindingRelationships>())
            {
                relationship.Row.TargetModel = RequireTarget(
                    loadIndexes.ModelReferenceListById,
                    relationship.TargetModelId,
                    "PropertyBinding",
                    relationship.Row.Id,
                    "TargetModelId");
            }

        }

        private static readonly string[] ShardFileNames =
        {
            "ModelReference.xml",
            "PropertyBinding.xml",
        };

        private static HashSet<string> BuildExpectedShardPaths(string instanceDirectoryPath)
        {
            var expectedShardPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var shardFileName in ShardFileNames)
            {
                expectedShardPaths.Add(Path.GetFullPath(Path.Combine(instanceDirectoryPath, shardFileName)));
            }

            return expectedShardPaths;
        }

        private sealed class LoadState
        {
            private HashSet<string>? modelReferenceIds;

            public void AddModelReferenceId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'ModelReference' contains a row with empty Id.");
                modelReferenceIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!modelReferenceIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'ModelReference' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? propertyBindingIds;

            public void AddPropertyBindingId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'PropertyBinding' contains a row with empty Id.");
                propertyBindingIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!propertyBindingIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'PropertyBinding' contains duplicate Id '{normalizedId}'.");
                }
            }

        }

        private sealed class LoadIndexes
        {
            private readonly MetaWeaveModel model;

            public LoadIndexes(MetaWeaveModel model)
            {
                this.model = model;
            }

            private Dictionary<string, ModelReference>? modelReferenceListById;

            public Dictionary<string, ModelReference> ModelReferenceListById => modelReferenceListById ??= BuildById(model.ModelReferenceList, row => row.Id, "ModelReference");

            private Dictionary<string, PropertyBinding>? propertyBindingListById;

            public Dictionary<string, PropertyBinding> PropertyBindingListById => propertyBindingListById ??= BuildById(model.PropertyBindingList, row => row.Id, "PropertyBinding");

        }

        private sealed class SaveIndexes
        {
            private readonly MetaWeaveModel model;

            public SaveIndexes(MetaWeaveModel model)
            {
                this.model = model;
            }

            private Dictionary<string, ModelReference>? modelReferenceListById;

            public Dictionary<string, ModelReference> ModelReferenceListById => modelReferenceListById ??= BuildById(model.ModelReferenceList, row => row.Id, "ModelReference");

            private Dictionary<string, PropertyBinding>? propertyBindingListById;

            public Dictionary<string, PropertyBinding> PropertyBindingListById => propertyBindingListById ??= BuildById(model.PropertyBindingList, row => row.Id, "PropertyBinding");

        }

        private static readonly Lazy<bool> RuntimeExtendedShape = new(DetectRuntimeExtendedShape);

        private static bool HasRuntimeExtendedShape()
        {
            return RuntimeExtendedShape.Value;
        }

        private static bool DetectRuntimeExtendedShape()
        {
            if (HasRuntimeExtendedEntityShapeGroup1())
            {
                return true;
            }

            return HasUnexpectedModelLists();
        }

        private static bool HasRuntimeExtendedEntityShapeGroup1()
        {
            if (HasUnexpectedProperties(typeof(ModelReference),
                "Id",
                "Alias",
                "ModelName",
                "WorkspacePath"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(PropertyBinding),
                "Id",
                "Name",
                "SourceEntity",
                "SourceProperty",
                "TargetEntity",
                "TargetProperty",
                "SourceModel",
                "TargetModel"))
            {
                return true;
            }

            return false;
        }

        private static bool HasUnexpectedModelLists()
        {
            var knownLists = new HashSet<string>(StringComparer.Ordinal)
            {
                "ModelReferenceList",
                "PropertyBindingList",
            };
            return typeof(MetaWeaveModel).GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Any(property =>
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(List<>) &&
                    !knownLists.Contains(property.Name));
        }

        private static bool HasUnexpectedProperties(Type type, params string[] knownProperties)
        {
            return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanRead && property.CanWrite && property.GetIndexParameters().Length == 0)
                .Any(property => !knownProperties.Contains(property.Name, StringComparer.Ordinal));
        }

        private static Dictionary<string, T> BuildById<T>(IEnumerable<T> rows, Func<T, string> getId, string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }
            return rowsById;
        }

        private static T RequireTarget<T>(Dictionary<string, T> rowsById, string targetId, string sourceEntityName, string sourceId, string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidDataException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }
            return target;
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var normalizedValue = value?.Trim() ?? string.Empty;
            if (string.IsNullOrEmpty(normalizedValue))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return normalizedValue;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return value;
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string indent)
        {
            builder.Append(indent);
            builder.Append('<');
            builder.Append(name);
            builder.Append('>');
            AppendXmlText(builder, value);
            builder.Append("</");
            builder.Append(name);
            builder.Append(">\n");
        }

        private static void AppendXmlAttribute(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    case '"': builder.Append("&quot;"); break;
                    case '\'': builder.Append("&apos;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static void AppendXmlText(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static bool IsNamespaceDeclaration(XmlReader reader)
        {
            return string.Equals(reader.Prefix, "xmlns", StringComparison.Ordinal) ||
                   string.Equals(reader.LocalName, "xmlns", StringComparison.Ordinal);
        }

        private static void DeleteIfExists(string path)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

    }

}
