// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaWeave
{
    public sealed class ModelReference
    {
        public string Id { get; set; } = string.Empty;

        public string Alias { get; set; } = string.Empty;

        public string ModelName { get; set; } = string.Empty;

        public string WorkspacePath { get; set; } = string.Empty;

    }
}
