// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaWeave
{
    public sealed class PropertyBinding
    {
        public string Id { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string SourceEntity { get; set; } = string.Empty;

        public string SourceProperty { get; set; } = string.Empty;

        public string TargetEntity { get; set; } = string.Empty;

        public string TargetProperty { get; set; } = string.Empty;

        public ModelReference SourceModel { get; set; } = null!;

        public ModelReference TargetModel { get; set; } = null!;

    }
}
